// generated by TRY COFFEESCRIPT at http://coffeescript.org/
var Hello, HelloWorldSystem, World, XholonClass, h, hws, w,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

XholonClass = (function() {
  function XholonClass() {}

  XholonClass.prototype.first = function(firstChild) {
    this.firstChild = firstChild;
  };

  XholonClass.prototype.next = function(nextSibling) {
    this.nextSibling = nextSibling;
  };

  XholonClass.prototype.port = function(port) {
    this.port = port;
  };

  return XholonClass;

})();

HelloWorldSystem = (function(_super) {
  __extends(HelloWorldSystem, _super);

  function HelloWorldSystem(State) {
    this.State = State;
  }

  return HelloWorldSystem;

})(XholonClass);

Hello = (function(_super) {
  __extends(Hello, _super);

  function Hello(State) {
    this.State = State;
  }

  return Hello;

})(XholonClass);

World = (function(_super) {
  __extends(World, _super);

  function World(State) {
    this.State = State;
  }

  return World;

})(XholonClass);

hws = new HelloWorldSystem(0);

h = new Hello(0);

hws.first(h);

w = new World(0);

h.next(w);

h.port(w);

w.port(h);

console.log(hws);

console.log(h);

console.log(w);
