/* Xholon Runtime Framework - executes event-driven & dynamic applications
 * Copyright (C) 2012 Ken Webb
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

package org.primordion.ef;

//import java.io.File;
//import java.io.IOException;
//import java.io.Writer;
//import java.security.AccessControlException;
import java.util.Date;

import org.primordion.xholon.base.IXholon;
//import org.primordion.xholon.base.Xholon;
import org.primordion.xholon.io.xml.IXholon2Xml;
import org.primordion.xholon.io.xml.XmlPrettyPrinter;
import org.primordion.xholon.service.ef.IXholon2ExternalFormat;
//import org.primordion.xholon.util.MiscIo;

/**
 * Export a Xholon model in XML format.
 * @author <a href="mailto:ken@primordion.com">Ken Webb</a>
 * @see <a href="http://www.primordion.com/Xholon">Xholon Project website</a>
 * @since 0.8.1 (Created on August 22, 2012)
 */
@SuppressWarnings("serial")
public class Xholon2Xml extends AbstractXholon2ExternalFormat implements IXholon2ExternalFormat {

	private String outFileName;
	private String outPath = "./ef/xml/";
	private String modelName;
	private IXholon root;
	//private Writer out;
	private StringBuilder sb;
	
	/** Current date and time. */
	private Date timeNow;
	private long timeStamp;
	
	//private boolean shouldPrettyPrint = true;
	
	/**
	 * Constructor
	 */
	public Xholon2Xml() {}
	
	@Override
	public String getVal_String() {
	  return sb.toString();
	}
	
	/*
	 * @see org.primordion.ef.IXholon2ExternalFormat#initialize(java.lang.String, java.lang.String, org.primordion.xholon.base.IXholon)
	 */
	public boolean initialize(String outFileName, String modelName, IXholon root) {
		timeNow = new Date();
		timeStamp = timeNow.getTime();
		if (outFileName == null) {
			this.outFileName = outPath + root.getXhcName() + "_" + root.getId() + "_" + timeStamp + ".xml";
		}
		else {
			this.outFileName = outFileName;
		}
		this.modelName = modelName;
		this.root = root;
		return true;
	}

	/*
	 * @see org.primordion.ef.IXholon2ExternalFormat#writeAll()
	 */
	public void writeAll() {
		/*boolean shouldClose = true;
		if (root.getApp().isUseAppOut()) {
			out = root.getApp().getOut();
			shouldClose = false;
		}
		else {
			try {
				// create any missing output directories
				File dirOut = new File(outPath);
				dirOut.mkdirs(); // will create a new directory only if there is no existing one
				out = MiscIo.openOutputFile(outFileName);
			} catch(AccessControlException e) {
				//out = new PrintWriter(System.out);
				out = root.getApp().getOut();
				shouldClose = false;
			}
		}*/
		sb = new StringBuilder();
		//try {
			sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
			if (isShouldWriteLinks()) {
				sb.append("<!-- To view this file, open it in a text or XML editor -->\n");
				sb.append(
					"<!--\nAutomatically generated by Xholon version 0.9.1, using Xholon2Xml.java\n"
					+ new Date() + " " + timeStamp + "\n"
					+ "model: " + modelName + "\n"
					+ "www.primordion.com/Xholon\n-->\n");
			}
			IXholon2Xml xholon2Xml = root.getXholon2Xml();
			xholon2Xml.setXhAttrStyle(this.getXhAttrStyle()); //(IXholon2Xml.XHATTR_TO_XMLELEMENT);
			xholon2Xml.setNameTemplate(this.getNameTemplate());
			xholon2Xml.setXhAttrReturnAll(this.getXhAttrReturnAll());
			xholon2Xml.setWriteStartDocument(this.isWriteStartDocument()); //(false);
			xholon2Xml.setWriteXholonId(this.isWriteXholonId());
			xholon2Xml.setWriteXholonRoleName(this.isWriteXholonRoleName());
			xholon2Xml.setWritePorts(this.isWritePorts());
			xholon2Xml.setWriteAnnotations(this.isWriteAnnotations());
			xholon2Xml.setWriteAttributes(this.isWriteAttributes());
			xholon2Xml.setWriteStandardAttributes(this.isWriteStandardAttributes());
			//root.consoleLog("ef.Xholon2Xml MAYBE about to set Val and AllPorts");
			//root.consoleLog(xholon2Xml.getClass().getName());
			if (xholon2Xml instanceof org.primordion.xholon.io.xml.Xholon2Xml) {
			  //root.consoleLog("ef.Xholon2Xml about to set Val and AllPorts");
			  //root.consoleLog(this.isShouldWriteVal());
			  //root.consoleLog(this.isShouldWriteAllPorts());
			  ((org.primordion.xholon.io.xml.Xholon2Xml)xholon2Xml)
			    .setShouldWriteVal(this.isShouldWriteVal());
			  ((org.primordion.xholon.io.xml.Xholon2Xml)xholon2Xml)
			    .setShouldWriteAllPorts(this.isShouldWriteAllPorts());
			}
			String xmlString = xholon2Xml.xholon2XmlString(root);
			if (isShouldPrettyPrint()) {
				XmlPrettyPrinter p = new XmlPrettyPrinter();
				p.setOmitXmlDeclaration("yes");
				xmlString = p.format(xmlString);
			}
			//out.write(sb.toString());
			//out.write(xmlString);
			//out.flush();
			sb.append(xmlString);
			writeToTarget(sb.toString(), outFileName, outPath, root);
		//} catch (IOException e) {
		//	Xholon.getLogger().error("", e);
		//}
		//if (shouldClose) {
		//	MiscIo.closeOutputFile(out);
		//}
	}
	
	/**
   * Make a JavaScript object with all the parameters for this external format.
   */
  protected native void makeEfParams() /*-{
    var p = {};
    //p.shouldShowStateMachineEntities = false;
    p.xhAttrStyle = 1;
    p.nameTemplate = "^^C^^^";
    p.xhAttrReturnAll = true;
    p.writeStartDocument = false;
    p.writeXholonId = false;
	  p.writeXholonRoleName = true;
	  p.writePorts = false;
    p.writeAnnotations = true;
    p.shouldPrettyPrint = true;
    p.writeAttributes = true;
    p.writeStandardAttributes = true;
    p.shouldWriteVal = false;
    p.shouldWriteAllPorts = false;
    p.shouldWriteLinks = false;
    p.showComments = true;
    this.efParams = p;
  }-*/;

	public native boolean isShouldPrettyPrint() /*-{return this.efParams.shouldPrettyPrint;}-*/;
	//public native void setShouldPrettyPrint(boolean shouldPrettyPrint) /*-{this.efParams.shouldPrettyPrint = shouldPrettyPrint;}-*/;
	
	/**
	 * 0 XHATTR_TO_NULL
	 * 1 XHATTR_TO_XMLATTR
	 * 2 XHATTR_TO_XMLELEMENT
	 */
	public native int getXhAttrStyle() /*-{return this.efParams.xhAttrStyle;}-*/;
	
  public native String getNameTemplate() /*-{return this.efParams.nameTemplate;}-*/;
  public native boolean getXhAttrReturnAll() /*-{return this.efParams.xhAttrReturnAll;}-*/;
  public native boolean isWriteStartDocument() /*-{return this.efParams.writeStartDocument;}-*/;
  public native boolean isWriteXholonId() /*-{return this.efParams.writeXholonId;}-*/;
	public native boolean isWriteXholonRoleName() /*-{return this.efParams.writeXholonRoleName;}-*/;
	public native boolean isWritePorts() /*-{return this.efParams.writePorts;}-*/;
	public native boolean isWriteAnnotations() /*-{return this.efParams.writeAnnotations;}-*/;
	public native boolean isWriteAttributes() /*-{return this.efParams.writeAttributes;}-*/;
	public native boolean isWriteStandardAttributes() /*-{return this.efParams.writeStandardAttributes;}-*/;
	public native boolean isShouldWriteVal() /*-{return this.efParams.shouldWriteVal;}-*/;
  public native boolean isShouldWriteAllPorts() /*-{return this.efParams.shouldWriteAllPorts;}-*/;
  public native boolean isShouldWriteLinks() /*-{return this.efParams.shouldWriteLinks;}-*/;
  public native boolean isShowComments() /*-{return this.efParams.showComments;}-*/;
  
}
