// DO NOT MODIFY.
// Automatically generated by Sbml2Cellontro from ./sbml/Brusselator.xml
// Thu Jan 18 18:01:31 EST 2007

package org.primordion.cellontro.app.sbml;

public interface CeBrusselator {

    public static final int XholonClassCE = 0;
    public static final int SbmlCompartmentCE = 1;
    public static final int compartmentCE = 2;
    public static final int SpeciesCE = 3;
    public static final int XCE = 4;
    public static final int YCE = 5;
    public static final int ECE = 6;
    public static final int DCE = 7;
    public static final int BCE = 8;
    public static final int ACE = 9;
    public static final int ReactionCE = 10;
    public static final int R1CE = 11;
    public static final int R2CE = 12;
    public static final int R3CE = 13;
    public static final int R4CE = 14;
}
