// DO NOT MODIFY.
// Automatically generated by Sbml2Cellontro from ./sbml/CellModel.xml
// Wed Dec 13 13:23:22 EST 2006

package org.primordion.cellontro.app.sbml;

public interface CeCellModel {

    public static final int XholonClassCE = 0;
    public static final int SbmlCompartmentCE = 1;
    public static final int ExtraCellularSpaceCE = 2;
    public static final int ExtraCellularSolutionCE = 3;
    public static final int EukaryoticCellCE = 4;
    public static final int CellMembraneCE = 5;
    public static final int CytoplasmCE = 6;
    public static final int CytosolCE = 7;
    public static final int MitochondrionCE = 8;
    public static final int MitochondrialDualMembraneCE = 9;
    public static final int MitochondrialOuterMembraneCE = 10;
    public static final int MitochondrialIntermembraneSpaceCE = 11;
    public static final int MitochondrialIntermembranesolCE = 12;
    public static final int MitochondrialInnerMembraneCE = 13;
    public static final int MatrixCE = 14;
    public static final int MatrixsolCE = 15;
    public static final int NucleusCE = 16;
    public static final int SpeciesCE = 17;
    public static final int WaterCE = 18;
    public static final int GlucoseCE = 19;
    public static final int Glucose_6_PhosphateCE = 20;
    public static final int Fructose_6_PhosphateCE = 21;
    public static final int Fructose_1x6_BiphosphateCE = 22;
    public static final int DihydroxyacetonePhosphateCE = 23;
    public static final int Glyceraldehyde_3_PhosphateCE = 24;
    public static final int X1x3_BisphosphoGlycerateCE = 25;
    public static final int X3_PhosphoGlycerateCE = 26;
    public static final int X2_PhosphoGlycerateCE = 27;
    public static final int PhosphoEnolPyruvateCE = 28;
    public static final int PyruvateCE = 29;
    public static final int AcetylCoACE = 30;
    public static final int CitrateCE = 31;
    public static final int IsocitrateCE = 32;
    public static final int A_KetoglutarateCE = 33;
    public static final int SuccinylCoaCE = 34;
    public static final int SuccinateCE = 35;
    public static final int FumarateCE = 36;
    public static final int MalateCE = 37;
    public static final int OxaloacetateCE = 38;
    public static final int ReactionCE = 39;
    public static final int CellBilayerCE = 40;
    public static final int MitochondrialOuterBilayerCE = 41;
    public static final int MitochondrialInnerBilayerCE = 42;
    public static final int PyruvateTransporterCE = 43;
    public static final int PyruvateDehydrogenaseCE = 44;
    public static final int CitrateSynthaseCE = 45;
    public static final int AconitaseCE = 46;
    public static final int IsocitrateDehydrogenaseCE = 47;
    public static final int A_KetoglutarateDehydrogenaseCE = 48;
    public static final int SuccinylCoASynthetaseCE = 49;
    public static final int SuccinateDehydrogenaseCE = 50;
    public static final int FumarateHydrataseCE = 51;
    public static final int MalateDehydrogenaseCE = 52;
    public static final int HexokinaseCE = 53;
    public static final int PhosphoGlucoIsomeraseCE = 54;
    public static final int PhosphoFructokinaseCE = 55;
    public static final int AldolaseCE = 56;
    public static final int TriosePhosphateIsomeraseCE = 57;
    public static final int Glyceraldehyde_3_phosphateDehydrogenaseCE = 58;
    public static final int PhosphoGlycerokinaseCE = 59;
    public static final int PhosphoGlyceromutaseCE = 60;
    public static final int EnolaseCE = 61;
    public static final int PyruvateKinaseCE = 62;
}
