// DO NOT MODIFY.
// Automatically generated by Sbml2Cellontro from ./sbml/CircadianClock.xml
// Thu Jan 18 16:21:29 EST 2007

package org.primordion.cellontro.app.sbml;

public interface CeCircadianClock {

    public static final int XholonClassCE = 0;
    public static final int SbmlCompartmentCE = 1;
    public static final int cellCE = 2;
    public static final int SpeciesCE = 3;
    public static final int P0CE = 4;
    public static final int MtCE = 5;
    public static final int MpCE = 6;
    public static final int T0CE = 7;
    public static final int P1CE = 8;
    public static final int P2CE = 9;
    public static final int T1CE = 10;
    public static final int T2CE = 11;
    public static final int CCE = 12;
    public static final int CnCE = 13;
    public static final int ReactionCE = 14;
    public static final int sPCE = 15;
    public static final int Mp_transcriptionCE = 16;
    public static final int Mp_degradationCE = 17;
    public static final int Mt_transcriptionCE = 18;
    public static final int Mt_degradationCE = 19;
    public static final int sTCE = 20;
    public static final int _1PCE = 21;
    public static final int _2PCE = 22;
    public static final int _3PCE = 23;
    public static final int _4PCE = 24;
    public static final int _1TCE = 25;
    public static final int _2TCE = 26;
    public static final int _3TCE = 27;
    public static final int _4TCE = 28;
    public static final int dPCE = 29;
    public static final int dTCE = 30;
    public static final int Mt_dilutionCE = 31;
    public static final int Mp_dilutionCE = 32;
    public static final int P0_dilutionCE = 33;
    public static final int P1_dilutionCE = 34;
    public static final int P2_dilutionCE = 35;
    public static final int T0_dilutionCE = 36;
    public static final int T1_dilutionCE = 37;
    public static final int T2_dilutionCE = 38;
    public static final int C_dilutionCE = 39;
    public static final int Cn_dilutionCE = 40;
    public static final int T2_degradationCE = 41;
    public static final int P2_degradationCE = 42;
    public static final int PT_binding_forwardCE = 43;
    public static final int PT_binding_backwardCE = 44;
    public static final int C_transport_forwardCE = 45;
    public static final int C_transport_backwardCE = 46;
}
