// DO NOT MODIFY.
// Automatically generated by Sbml2Cellontro from ./sbml/DimericMWCstiff.xml
// Thu Jan 18 19:24:48 EST 2007

package org.primordion.cellontro.app.sbml;

public interface CeDimericMWCstiff {

    public static final int XholonClassCE = 0;
    public static final int SbmlCompartmentCE = 1;
    public static final int cellCE = 2;
    public static final int SpeciesCE = 3;
    public static final int R0CE = 4;
    public static final int T0CE = 5;
    public static final int R1CE = 6;
    public static final int SCE = 7;
    public static final int PCE = 8;
    public static final int R2CE = 9;
    public static final int ReactionCE = 10;
    public static final int reaction1CE = 11;
    public static final int reaction2CE = 12;
    public static final int reaction3CE = 13;
    public static final int reaction4CE = 14;
    public static final int reaction7CE = 15;
    public static final int reaction6CE = 16;
    public static final int reaction5CE = 17;
    public static final int reaction8CE = 18;
}
