// DO NOT MODIFY.
// Automatically generated by Sbml2Cellontro from ./sbml/YeastGly.xml
// Thu Jan 18 19:00:19 EST 2007

package org.primordion.cellontro.app.sbml;

public interface CeYeastGlyPritchardKel {

    public static final int XholonClassCE = 0;
    public static final int SbmlCompartmentCE = 1;
    public static final int compartmentCE = 2;
    public static final int SpeciesCE = 3;
    public static final int GLCiCE = 4;
    public static final int ATPCE = 5;
    public static final int G6PCE = 6;
    public static final int ADPCE = 7;
    public static final int F6PCE = 8;
    public static final int F16bPCE = 9;
    public static final int AMPCE = 10;
    public static final int DHAPCE = 11;
    public static final int GAPCE = 12;
    public static final int NADCE = 13;
    public static final int BPGCE = 14;
    public static final int NADHCE = 15;
    public static final int P3GCE = 16;
    public static final int P2GCE = 17;
    public static final int PEPCE = 18;
    public static final int PYRCE = 19;
    public static final int AcAldCE = 20;
    public static final int SuccinateCE = 21;
    public static final int TrehaloseCE = 22;
    public static final int GlycogenCE = 23;
    public static final int GlycerolCE = 24;
    public static final int EtOHCE = 25;
    public static final int CO2CE = 26;
    public static final int F26bPCE = 27;
    public static final int GLCoCE = 28;
    public static final int ReactionCE = 29;
    public static final int HXTCE = 30;
    public static final int HKCE = 31;
    public static final int PGICE = 32;
    public static final int PFKCE = 33;
    public static final int ALDCE = 34;
    public static final int TPICE = 35;
    public static final int GAPDHCE = 36;
    public static final int PGKCE = 37;
    public static final int PGMCE = 38;
    public static final int ENOCE = 39;
    public static final int PYKCE = 40;
    public static final int PDCCE = 41;
    public static final int ADHCE = 42;
    public static final int ATPaseCE = 43;
    public static final int AKCE = 44;
    public static final int G3PDHCE = 45;
    public static final int Glycogen_BranchCE = 46;
    public static final int Trehalose_BranchCE = 47;
    public static final int Succinate_BranchCE = 48;
}
