#!/bin/bash
# Xholon Runtime Framework - executes event-driven & dynamic applications
# Copyright (C) 2005, 2006, 2007 Ken Webb
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2.1
# of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA

# Transform MagicDraw UML XMI files to Xholon format.
# Tested with MagicDraw 11.5
# Ken Webb  www.primordion.com/Xholon
# xmi2xh
# September 26, 2007

java -classpath ../../bin:../../lib/Xholon.jar:../../lib/ecj.jar org.primordion.xholon.io.Xmi2Xholon $1 $2 $3 $4
