/* Xholon Runtime Framework - executes event-driven & dynamic applications
 * Copyright (C) 2015 Ken Webb
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

package org.primordion.ef.other;

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import org.primordion.xholon.base.Annotation;
import org.primordion.xholon.base.IXholon;
import org.primordion.xholon.base.PortInformation;
import org.primordion.ef.AbstractXholon2ExternalFormat;
import org.primordion.xholon.io.gwt.HtmlScriptHelper;
import org.primordion.xholon.service.IXholonService;
import org.primordion.xholon.service.XholonDirectoryService;
import org.primordion.xholon.service.ef.IXholon2GraphFormat;

/**
 * Export a Xholon model in Twine Archive format.
 * "Twine is an open-source tool for telling interactive, nonlinear stories."
 * Twine doesn't have a concept of hierarchy.
 * But have options to show hierarchy using links.
 *   maybe also direct links to all children
 *   maybe reverse links from reffed nodes back to nodes that ref them
 * TODO
 *  use [[viewableText | link]] syntax
 *
 * @author <a href="mailto:ken@primordion.com">Ken Webb</a>
 * @see <a href="http://www.primordion.com/Xholon">Xholon Project website</a>
 * @since 0.9.1 (Created on March 10, 2015)
 * @see <a href="http://twinery.org">Twine site</a>
 */
@SuppressWarnings("serial")
public class Xholon2Twine extends AbstractXholon2ExternalFormat implements IXholon2GraphFormat {
  
  /** StringBuilder initial capacity. */
  protected static final int SB_INITIAL_CAPACITY = 1000; // default is 16
  
  protected static final String TW_STORYDATA = "tw-storydata";
  protected static final String TW_PASSAGEDATA = "tw-passagedata";
  
  private String outFileName;
  private String outPath = "./ef/twine/";
  private String modelName;
  private IXholon root;
  
  /** Current date and time. */
  private Date timeNow;
  private long timeStamp;
  
  /**
   * Start of the Twine archive.
   */
  protected StringBuilder startSb = null;
  
  /**
   * The accumulating text for all Twine passage nodes.
   */
  protected StringBuilder nodeSb = null;
  
  /**
   * End of the Twine archive.
   */
  protected StringBuilder endSb = null;
  
  /** Annotation service. */
  protected IXholon annService = null;
  
  /**
   * Constructor.
   */
  public Xholon2Twine() {}
  
  @Override
  public boolean initialize(String outFileName, String modelName, IXholon root) {
    timeNow = new Date();
    timeStamp = timeNow.getTime();
    if (outFileName == null) {
      this.outFileName = outPath + root.getXhcName() + "_" + root.getId() + "_" + timeStamp + ".xml";
    }
    else {
      this.outFileName = outFileName;
    }
    this.modelName = modelName;
    this.root = root;
    
    // <tw-storydata name="Kenz Test A" startnode="1" creator="Twine" creator-version="2.0.3" format="Harlowe" options="">
    this.startSb = new StringBuilder(SB_INITIAL_CAPACITY)
    .append("<!-- \n")
    .append("Automatically generated by Xholon version 0.9.1, using org.primordion.ef.Xholon2Twine.java\n")
    .append(timeNow)
    .append("\nmodel: ").append(modelName).append("\n")
    .append("www.primordion.com/Xholon/gwt/\n")
    .append("To view this file, import it into Twine 2, at http://twinery.org\n")
    .append("-->\n\n")
    
    .append("<").append(TW_STORYDATA)
    .append(" name=\"").append(modelName)
    .append("\" startnode=\"").append(this.root.getId()) // this can be changed later, in the file or with Twine
    .append("\" creator=\"").append("Twine")
    .append("\" creator-version=\"").append(this.getTwineVersion());
    if (this.getFormat().length() > 0) {
      startSb.append("\" format=\"").append(this.getFormat());
    }
    startSb.append("\" options=\"").append(this.getOptions())
    .append("\">\n")
    .append("<style role=\"stylesheet\" id=\"twine-user-stylesheet\" type=\"text/twine-css\"></style>\n")
    .append("<script role=\"script\" id=\"twine-user-script\" type=\"text/twine-javascript\"></script>\n")
    ;
    
    this.nodeSb = new StringBuilder(SB_INITIAL_CAPACITY);
    
    // </tw-storydata>
    this.endSb = new StringBuilder(128)
    .append("</").append(TW_STORYDATA).append(">")
    .append("\n");
    
    return true;
  }

  @Override
  public void writeAll() {
    writeNode(root);
    StringBuilder sb = new StringBuilder()
    .append(startSb.toString())
    .append(nodeSb.toString())
    .append(endSb.toString());
    
    writeToTarget(sb.toString(), outFileName, outPath, root);
    
  }

  @Override
  public void writeNode(IXholon xhNode) {
    // xhNode details
    writeNodeDetails(xhNode);
    // xhNode children
    IXholon childNode = xhNode.getFirstChild();
    while (childNode != null) {
      writeNode(childNode);
      childNode = childNode.getNextSibling();
    }
  }
  
  /**
   * Write details for one node.
   * <tw-passagedata pid="1" name="Helloo" tags="" position="1,1">Helloo iz the first word in the phrase Helloo [[Worldd]].</tw-passagedata>
   */
  protected void writeNodeDetails(IXholon xhNode) {
    nodeSb.append("<").append(TW_PASSAGEDATA)
    .append(" pid=\"").append(xhNode.getId())
    .append("\" name=\"").append(makeNodeName(xhNode))
    .append("\" tags=\"").append("")
    .append("\" position=\"").append(makePosX(xhNode)).append(",").append(makePosY(xhNode)).append("\">")
    ;
    if (isShowNodeName()) {
      nodeSb.append("\n").append(makeNodeName(xhNode));
    }
    String anno = findAnnotation(xhNode);
    if ((anno != null) && isShowAnnotations()) {
      // add Xholon annotations
      nodeSb.append("\n").append(anno);
    }
    if (isShowAttributes()) {
      writeNodeAttributes(xhNode);
    }
    // xhNode outgoing links
    writeEdges(xhNode);
    nodeSb.append("</").append(TW_PASSAGEDATA).append(">\n")
    ;
  }
  
  @SuppressWarnings("unchecked")
  @Override
  public void writeEdges(IXholon xhNode) {
    // write Xholon ports
    List<PortInformation> portList = null;
    switch (getShowPorts()) {
    case 1:
      portList = new org.primordion.xholon.base.ReflectionJavaMicro().getAllPorts(xhNode, false);
      break;
    case 2:
      portList = xhNode.getAllPorts(); // used in Xholon2MindMap
      break;
    case 0:
    default:
      portList = new ArrayList<PortInformation>(); // zero-length list
      break;
    }
    for (int i = 0; i < portList.size(); i++) {
      PortInformation pi = (PortInformation)portList.get(i);
      IXholon reffedNode = pi.getReffedNode();
      nodeSb
      .append("\n");
      ;
      if (isScopeToRoot()) {
        // don't write port if it's not within scope of the root node
        if (!reffedNode.hasAncestor(root.getName())) {
          continue;
        }
      }
      if (isShowPortName()) {
        String fieldName = pi.getFieldName();
        nodeSb.append(fieldName);
        if ("port".equals(fieldName)) {
          nodeSb.append(pi.getFieldNameIndexStr());
        }
        nodeSb.append(" ");
      }
      nodeSb.append("[[")
      .append(makeNodeName(reffedNode))
      .append("]]");
    }
    if (portList.size() > 0) {
      nodeSb.append("\n");
    }
    
    // optionally write parentNode  up
    if (isShowParentLink() && (xhNode != root)) {
      IXholon parent = xhNode.getParentNode();
      if (parent != null) {
        nodeSb.append("\nGo to parent [[")
        .append(makeNodeName(parent))
        .append("]]");
      }
    }
    
    // optionally write previousSibling  left
    if (isShowPrevSiblingLink() && (xhNode != root)) {
      IXholon prev = xhNode.getPreviousSibling();
      if (prev != null) {
        nodeSb.append("\nGo to previous sibling [[")
        .append(makeNodeName(prev))
        .append("]]");
      }
    }
    
    // optionally write nextSibling  right
    if (isShowNextSiblingLink() && (xhNode != root)) {
      IXholon next = xhNode.getNextSibling();
      if (next != null) {
        nodeSb.append("\nGo to next sibling [[")
        .append(makeNodeName(next))
        .append("]]");
      }
    }
    
    // optionally write firstChild  down
    if (isShowFirstChildLink()) {
      IXholon first = xhNode.getFirstChild();
      if (first != null) {
        nodeSb.append("\nGo to first child [[")
        .append(makeNodeName(first))
        .append("]]");
      }
    }
    
  }

  @Override
  public void writeNodeAttributes(IXholon xhNode) {
    double val = xhNode.getVal();
    if ((val != 0.0) && (val != Double.MIN_VALUE) && (val != Double.MAX_VALUE)) {
      nodeSb.append("\nval ").append(val);
    }
    // TODO
  }
  
  /**
   * Make a standard name for a node.
   * @param xhNode 
   * @return a standard name
   */
  protected String makeNodeName(IXholon xhNode) {
    // optionally convert underlines to another character(s)
    String nodeName = xhNode.getName(getNameTemplate());
    if (getUnderlineReplacement().length() != 0) {
      nodeName = nodeName.replaceAll("_", getUnderlineReplacement());
    }
    return nodeName;
  }
  
  /**
   * Try to find a Xholon annotation for a node.
   * @param xhNode 
   * @return an annotation, or null
   */
  protected String findAnnotation(IXholon xhNode) {
    if (annService == null) {
      annService = xhNode.getService(IXholonService.XHSRV_XHOLON_DIRECTORY);
    }
    if (annService != null) {
      IXholon ann = (IXholon)((XholonDirectoryService)annService)
        .get(Annotation.makeUniqueKey(xhNode));
      if (ann != null) {
        return ann.getVal_String();
      }
    }
    return null;
  }
  
  // _jsdata.posx
  protected native double makePosX(IXholon xhNode) /*-{
    if ((typeof xhNode._jsdata == "undefined") || (typeof xhNode._jsdata.posx == "undefined")) {
      return xhNode.id();
    }
    return xhNode._jsdata.posx * this.efParams.posMultiplier;
  }-*/;
  
  // _jsdata.posy
  protected native double makePosY(IXholon xhNode) /*-{
    if ((typeof xhNode._jsdata == "undefined") || (typeof xhNode._jsdata.posy == "undefined")) {
      return xhNode.id();
    }
    return xhNode._jsdata.posy * this.efParams.posMultiplier;
  }-*/;
  
  /**
   * Make a JavaScript object with all the parameters for this external format.
   */
  protected native void makeEfParams() /*-{
    var p = {};
    p.twineVersion = "2.0.3";
    p.format = "Harlowe"; // Snowman
    p.options = "";
    p.showNodeName = true;
    p.showAnnotations = true;
    p.showAttributes = false;
    p.showPorts = 2; // 0=don't show  1=getPorts1  2=getPorts2
    p.showPortName = true;
    p.showParentLink = true;
    p.showPrevSiblingLink = false;
    p.showNextSiblingLink = true;
    p.showFirstChildLink = true;
    p.nameTemplate = "R^^_i^"; // "R^^^^^"
    p.underlineReplacement = "‗"; // "--" or "-" or " " or other (escapes don't work)
    p.scopeToRoot = true;
    p.posMultiplier = 2.0;
    this.efParams = p;
  }-*/;

  public native String getTwineVersion() /*-{return this.efParams.twineVersion;}-*/;
  //public native void setTwineVersion(String twineVersion) /*-{this.efParams.twineVersion = twineVersion;}-*/;

  public native String getFormat() /*-{return this.efParams.format;}-*/;
  //public native void setFormat(String format) /*-{this.efParams.format = format;}-*/;

  public native String getOptions() /*-{return this.efParams.options;}-*/;
  //public native void setOptions(String options) /*-{this.efParams.options = options;}-*/;

  public native boolean isShowNodeName() /*-{return this.efParams.showNodeName;}-*/;
  //public native void setShowNodeName(boolean showNodeName) /*-{this.efParams.showNodeName = showNodeName;}-*/;
  
  public native boolean isShowAnnotations() /*-{return this.efParams.showAnnotations;}-*/;
  //public native void setShowAnnotations(boolean showAnnotations) /*-{this.efParams.showAnnotations = showAnnotations;}-*/;
  
  public native boolean isShowAttributes() /*-{return this.efParams.showAttributes;}-*/;
  //public native void setShowAttributes(boolean showAttributes) /*-{this.efParams.showAttributes = showAttributes;}-*/;
  
  public native int getShowPorts() /*-{return this.efParams.showPorts;}-*/;
  //public native void setShowPorts(int showPorts) /*-{this.efParams.showPorts = showPorts;}-*/;
  
  /**
   * Whether or not a link should show the name of the port.
   */
  public native boolean isShowPortName() /*-{return this.efParams.showPortName;}-*/;
  //public native void setShowPortName(boolean showPortName) /*-{this.efParams.showPortName = showPortName;}-*/;
  
  public native boolean isShowFirstChildLink() /*-{return this.efParams.showFirstChildLink;}-*/;
  //public native void setShowFirstChildLink(boolean showFirstChildLink) /*-{this.efParams.showFirstChildLink = showFirstChildLink;}-*/;
  
  public native boolean isShowNextSiblingLink() /*-{return this.efParams.showNextSiblingLink;}-*/;
  //public native void setShowNextSiblingLink(boolean showNextSiblingLink) /*-{this.efParams.showNextSiblingLink = showNextSiblingLink;}-*/;
  
  public native boolean isShowPrevSiblingLink() /*-{return this.efParams.showPrevSiblingLink;}-*/;
  //public native void setShowPrevSiblingLink(boolean showPrevSiblingLink) /*-{this.efParams.showPrevSiblingLink = showPrevSiblingLink;}-*/;
  
  public native boolean isShowParentLink() /*-{return this.efParams.showParentLink;}-*/;
  //public native void setShowParentLink(boolean showParentLink) /*-{this.efParams.showParentLink = showParentLink;}-*/;
  
  public native String getNameTemplate() /*-{return this.efParams.nameTemplate;}-*/;
  //public native void setNameTemplate(String nameTemplate) /*-{this.efParams.nameTemplate = nameTemplate;}-*/;
  
  public native String getUnderlineReplacement() /*-{return this.efParams.underlineReplacement;}-*/;
  //public native void setUnderlineReplacement(String underlineReplacement) /*-{this.efParams.underlineReplacement = underlineReplacement;}-*/;

  public native boolean isScopeToRoot() /*-{return this.efParams.scopeToRoot;}-*/;
  //public native void setScopeToRoot(boolean scopeToRoot) /*-{this.efParams.scopeToRoot = scopeToRoot;}-*/;

  public native double getPosMultiplier() /*-{return this.efParams.posMultiplier;}-*/;
  //public native void setPosMultiplier(double posMultiplier) /*-{this.efParams.posMultiplier = posMultiplier;}-*/;
  
}
