<map version="freeplane 1.3.0">
<!--To view this file, download free mind mapping software Freeplane from http://freeplane.sourceforge.net -->
<node TEXT="Cat theory system" ID="47" CREATED="1496780719006" MODIFIED="1496784086805"><hook NAME="MapStyle" zoom="4.0">
    <properties show_icon_for_attributes="true" show_note_icons="true"/>

<map_styles>
<stylenode LOCALIZED_TEXT="styles.root_node">
<stylenode LOCALIZED_TEXT="styles.predefined" POSITION="right">
<stylenode LOCALIZED_TEXT="default" MAX_WIDTH="600" COLOR="#000000" STYLE="as_parent">
<font NAME="SansSerif" SIZE="10" BOLD="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.details"/>
<stylenode LOCALIZED_TEXT="defaultstyle.note"/>
<stylenode LOCALIZED_TEXT="defaultstyle.floating">
<edge STYLE="hide_edge"/>
<cloud COLOR="#f0f0f0" SHAPE="ROUND_RECT"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.user-defined" POSITION="right">
<stylenode LOCALIZED_TEXT="styles.topic" COLOR="#18898b" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subtopic" COLOR="#cc3300" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subsubtopic" COLOR="#669900">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.important">
<icon BUILTIN="yes"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.AutomaticLayout" POSITION="right">
<stylenode LOCALIZED_TEXT="AutomaticLayout.level.root" COLOR="#000000">
<font SIZE="18"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,1" COLOR="#0033ff">
<font SIZE="16"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,2" COLOR="#00b439">
<font SIZE="14"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,3" COLOR="#990000">
<font SIZE="12"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,4" COLOR="#111111">
<font SIZE="10"/>
</stylenode>
</stylenode>
</stylenode>
</map_styles>
</hook>
<edge WIDTH="1"/>
<hook NAME="accessories/plugins/AutomaticLayout.properties" VALUE="HEADINGS"/>
<cloud COLOR="#f0f0f0" SHAPE="ROUND_RECT"/>
<node TEXT="Strings" POSITION="right" ID="48" CREATED="1496780719006" MODIFIED="1496783739340"/>
<node TEXT="Nats" POSITION="right" ID="49" CREATED="1496780719006" MODIFIED="1496783739340"/>
<node TEXT="Employees" POSITION="right" ID="50" CREATED="1496780719006" MODIFIED="1496784538418">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="51" MIDDLE_LABEL="worksIn" STARTINCLINATION="40;0;" ENDINCLINATION="40;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="49" MIDDLE_LABEL="age" STARTINCLINATION="45;0;" ENDINCLINATION="45;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="49" MIDDLE_LABEL="cummulative_age" STARTINCLINATION="45;0;" ENDINCLINATION="45;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="48" MIDDLE_LABEL="first_" STARTINCLINATION="31;-9;" ENDINCLINATION="31;9;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="LINE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="9" FONT_FAMILY="SansSerif" DESTINATION="50" MIDDLE_LABEL="manager" STARTINCLINATION="40;0;" ENDINCLINATION="40;45;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="48" MIDDLE_LABEL="last_" STARTINCLINATION="84;0;" ENDINCLINATION="101;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<node TEXT="A  employee" ID="52" CREATED="1496780719006" MODIFIED="1496783739340">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="55" MIDDLE_LABEL="worksIn" STARTINCLINATION="40;0;" ENDINCLINATION="69;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="53" MIDDLE_LABEL="manager" STARTINCLINATION="40;0;" ENDINCLINATION="40;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
</node>
<node TEXT="B  employee" ID="53" CREATED="1496780719006" MODIFIED="1496783739340">
<arrowlink SHAPE="LINE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="53" MIDDLE_LABEL="manager" STARTINCLINATION="40;0;" ENDINCLINATION="40;45;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="55" MIDDLE_LABEL="worksIn" STARTINCLINATION="40;0;" ENDINCLINATION="51;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
</node>
<node TEXT="C  employee" ID="54" CREATED="1496780719006" MODIFIED="1496783739340">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="56" MIDDLE_LABEL="worksIn" STARTINCLINATION="40;0;" ENDINCLINATION="49;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="LINE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="54" MIDDLE_LABEL="manager" STARTINCLINATION="40;0;" ENDINCLINATION="40;45;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
</node>
</node>
<node TEXT="Departments" POSITION="right" ID="51" CREATED="1496780719006" MODIFIED="1496784239394">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="50" MIDDLE_LABEL="secretary" STARTINCLINATION="40;0;" ENDINCLINATION="40;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="48" MIDDLE_LABEL="name_" STARTINCLINATION="74;0;" ENDINCLINATION="74;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<node TEXT="M  department" ID="55" CREATED="1496780719006" MODIFIED="1496783739341">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="53" MIDDLE_LABEL="secretary" STARTINCLINATION="51;0;" ENDINCLINATION="40;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
</node>
<node TEXT="S  department" ID="56" CREATED="1496780719006" MODIFIED="1496783739341">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#6666ff" WIDTH="2" TRANSPARENCY="255" FONT_SIZE="6" FONT_FAMILY="SansSerif" DESTINATION="54" MIDDLE_LABEL="secretary" STARTINCLINATION="49;0;" ENDINCLINATION="40;0;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
</node>
</node>
</node>
</map>
