<map version="0.9.0">
<!-- To view this file, download free mind mapping software:
 FreeMind from http://freemind.sourceforge.net/wiki/index.php/Main_Page or
 Freeplane from http://freeplane.sourceforge.net/wiki/index.php/Main_Page

Automatically generated by Xholon version 0.9.1, using Xholon2MindMap.java
Wed May 15 12:31:13 GMT-400 2019 1557937873101
model: Hello World
www.primordion.com/Xholon
-->
<node CREATED="1557937873101" ID="0" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="1" POSITION="right" TEXT=" ">
<node CREATED="1557937873101" ID="2" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="3" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="4" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="5" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="6" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="7" POSITION="right" TEXT=" ">
<node CREATED="1557937873101" ID="47" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="50" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="8" POSITION="right" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="9" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="0" TEXT=" ">
<node CREATED="1557937873101" ID="2" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="3" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="0" TEXT=" ">
<node CREATED="1557937873101" ID="1" TEXT=" ">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="2" TEXT=" ">
<node CREATED="1557937873101" ID="4" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="51" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" ID="3" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="4" TEXT=" ">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="5" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="6" TEXT=" ">
<node CREATED="1557937873101" ID="5" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="6" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="7" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="8" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="9" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="7" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="8" TEXT=" ">
<node CREATED="1557937873101" ID="10" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="11" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="12" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="9" TEXT=" ">
<node CREATED="1557937873101" ID="1011202" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" ID="10" TEXT=" ">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="11" TEXT=" ">
<node CREATED="1557937873101" ID="46" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" ID="12" TEXT=" ">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="13" TEXT=" ">
<node CREATED="1557937873101" ID="48" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" ID="14" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="15" TEXT=" ">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="16" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="17" TEXT=" ">
<node CREATED="1557937873101" ID="13" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="14" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="15" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="16" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="17" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="18" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="19" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="20" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="21" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="22" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="23" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="24" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="25" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="26" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="27" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="28" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="29" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="30" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="31" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="32" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="33" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" ID="18" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="19" TEXT=" ">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="20" TEXT=" ">
<node CREATED="1557937873101" ID="21" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="22" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="23" TEXT=" ">
<node CREATED="1557937873101" ID="34" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="24" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="25" TEXT=" ">
<node CREATED="1557937873101" ID="35" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" ID="26" TEXT=" ">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="27" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="28" TEXT=" ">
<node CREATED="1557937873101" ID="36" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="37" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="38" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="39" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="40" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="29" TEXT=" ">
<node CREATED="1557937873101" ID="30" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="31" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="32" TEXT=" ">
<node CREATED="1557937873101" ID="41" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="33" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="34" TEXT=" ">
<node CREATED="1557937873101" ID="42" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="43" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="44" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="45" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="35" TEXT=" ">
<node CREATED="1557937873101" ID="36" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" ID="37" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="38" TEXT=" ">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="10" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="0" TEXT="Xholon class">
<node CREATED="1557937873101" FOLDED="true" ID="2000000" TEXT="Xholon mechanism">
<node CREATED="1557937873101" ID="2000001" TEXT="Xh mechanisms">
</node>
<node CREATED="1557937873101" ID="2000002" TEXT="Xholon mechanisms">
</node>
<node CREATED="1557937873101" ID="2000003" TEXT="User mechanisms">
</node>
<node CREATED="1557937873101" ID="2000004" TEXT="User mechanism">
</node>
<node CREATED="1557937873101" ID="1010000" TEXT="Annotation">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1002200" TEXT="Attribute">
<node CREATED="1557937873101" ID="1002201" TEXT="Attribute_attribute">
</node>
<node CREATED="1557937873101" ID="1002202" TEXT="Attribute_boolean">
</node>
<node CREATED="1557937873101" ID="1002203" TEXT="Attribute_byte">
</node>
<node CREATED="1557937873101" ID="1002204" TEXT="Attribute_char">
</node>
<node CREATED="1557937873101" ID="1002205" TEXT="Attribute_double">
</node>
<node CREATED="1557937873101" ID="1002206" TEXT="Attribute_float">
</node>
<node CREATED="1557937873101" ID="1002207" TEXT="Attribute_int">
</node>
<node CREATED="1557937873101" ID="1002208" TEXT="Attribute_long">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1002209" TEXT="Attribute_ object">
<node CREATED="1557937873101" ID="1014910" TEXT="Default">
</node>
</node>
<node CREATED="1557937873101" ID="1002210" TEXT="Attribute_short">
</node>
<node CREATED="1557937873101" ID="1002211" TEXT="Attribute_ string">
</node>
<node CREATED="1557937873101" ID="1002212" TEXT="Attribute_arrayboolean">
</node>
<node CREATED="1557937873101" ID="1002213" TEXT="Attribute_arraybyte">
</node>
<node CREATED="1557937873101" ID="1002214" TEXT="Attribute_arraychar">
</node>
<node CREATED="1557937873101" ID="1002215" TEXT="Attribute_arraydouble">
</node>
<node CREATED="1557937873101" ID="1002216" TEXT="Attribute_arrayfloat">
</node>
<node CREATED="1557937873101" ID="1002217" TEXT="Attribute_arrayint">
</node>
<node CREATED="1557937873101" ID="1002218" TEXT="Attribute_arraylong">
</node>
<node CREATED="1557937873101" ID="1002219" TEXT="Attribute_array object">
</node>
<node CREATED="1557937873101" ID="1002220" TEXT="Attribute_arrayshort">
</node>
<node CREATED="1557937873101" ID="1002221" TEXT="Attribute_array string">
</node>
<node CREATED="1557937873101" ID="1002222" TEXT="Attribute_ list">
</node>
<node CREATED="1557937873101" ID="1002223" TEXT="Attribute_ map">
</node>
<node CREATED="1557937873101" ID="1002224" TEXT="Attribute_ set">
</node>
<node CREATED="1557937873101" ID="1002225" TEXT="Attr: attribute_boolean">
</node>
<node CREATED="1557937873101" ID="1002226" TEXT="Attr: attribute_byte">
</node>
<node CREATED="1557937873101" ID="1002227" TEXT="Attr: attribute_char">
</node>
<node CREATED="1557937873101" ID="1002228" TEXT="Attr: attribute_double">
</node>
<node CREATED="1557937873101" ID="1002229" TEXT="Attr: attribute_float">
</node>
<node CREATED="1557937873101" ID="1002230" TEXT="Attr: attribute_int">
</node>
<node CREATED="1557937873101" ID="1002231" TEXT="Attr: attribute_long">
</node>
<node CREATED="1557937873101" ID="1002232" TEXT="Attr: attribute_ object">
</node>
<node CREATED="1557937873101" ID="1002233" TEXT="Attr: attribute_short">
</node>
<node CREATED="1557937873101" ID="1002234" TEXT="Attr: attribute_ string">
</node>
</node>
<node CREATED="1557937873101" ID="1014400" TEXT="Avatar">
</node>
<node CREATED="1557937873101" ID="1014401" TEXT="Chatbot">
</node>
<node CREATED="1557937873101" ID="1014402" TEXT="Sprite">
</node>
<node CREATED="1557937873101" ID="1014403" TEXT="Stage">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1001200" TEXT="Behavior">
<node CREATED="1557937873101" ID="1001201" TEXT="Opaque behavior">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013100" TEXT="Bigraph entity">
<node CREATED="1557937873101" ID="1013101" TEXT="Bigraphical reactive system">
</node>
<node CREATED="1557937873101" ID="1013102" TEXT="Bigraphs">
</node>
<node CREATED="1557937873101" ID="1013103" TEXT="Bigraph">
</node>
<node CREATED="1557937873101" ID="1013104" TEXT="Place graph">
</node>
<node CREATED="1557937873101" ID="1013105" TEXT="Link graph">
</node>
<node CREATED="1557937873101" ID="1013106" TEXT="Reaction rules b g">
</node>
<node CREATED="1557937873101" ID="1013107" TEXT="Reaction rule b g">
</node>
<node CREATED="1557937873101" ID="1013108" TEXT="Redex">
</node>
<node CREATED="1557937873101" ID="1013109" TEXT="Reactum">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013110" TEXT="Place b g">
<node CREATED="1557937873101" ID="1013111" TEXT="Root b g">
</node>
<node CREATED="1557937873101" ID="1013112" TEXT="Node b g">
</node>
</node>
<node CREATED="1557937873101" ID="1013113" TEXT="Site b g">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013114" TEXT="Link b g">
<node CREATED="1557937873101" ID="1013115" TEXT="Hyperedge b g">
</node>
<node CREATED="1557937873101" ID="1013116" TEXT="Outer name b g">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013117" TEXT="Point b g">
<node CREATED="1557937873101" ID="1013118" TEXT="Port b g">
</node>
<node CREATED="1557937873101" ID="1013119" TEXT="Inner name b g">
</node>
</node>
<node CREATED="1557937873101" ID="1013120" TEXT="Control b g">
</node>
<node CREATED="1557937873101" ID="1013121" TEXT="Composer b g">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1003200" TEXT="Bus app">
<node CREATED="1557937873101" ID="1003201" TEXT="App client m v c">
</node>
<node CREATED="1557937873101" ID="1003202" TEXT="App client model">
</node>
<node CREATED="1557937873101" ID="1003203" TEXT="App client view">
</node>
<node CREATED="1557937873101" ID="1003204" TEXT="App client controller">
</node>
<node CREATED="1557937873101" ID="1003205" TEXT="App client worker">
</node>
<node CREATED="1557937873101" ID="1003206" TEXT="App client business delegate">
</node>
<node CREATED="1557937873101" ID="1003207" TEXT="Bus app service">
</node>
<node CREATED="1557937873101" ID="1003208" TEXT="Bus app dao">
</node>
<node CREATED="1557937873101" ID="1003209" TEXT="Bus app ejb">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1015900" TEXT="Cat theory">
<node CREATED="1557937873101" ID="1015901" TEXT="Cat aql">
</node>
<node CREATED="1557937873101" ID="1015902" TEXT="Cat op dsl">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1004200" TEXT="Dfd entity">
<node CREATED="1557937873101" ID="1004201" TEXT="Dfd external entity">
</node>
<node CREATED="1557937873101" ID="1004202" TEXT="Dfd data flow">
</node>
<node CREATED="1557937873101" ID="1004203" TEXT="Dfd process">
</node>
<node CREATED="1557937873101" ID="1004204" TEXT="Dfd data store">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1004205" TEXT="Dfd container">
<node CREATED="1557937873101" ID="1004206" TEXT="Dfd external entities">
</node>
<node CREATED="1557937873101" ID="1004207" TEXT="Dfd data flows">
</node>
<node CREATED="1557937873101" ID="1004208" TEXT="Dfd processes">
</node>
<node CREATED="1557937873101" ID="1004209" TEXT="Dfd data stores">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1014900" TEXT="Gexf">
<node CREATED="1557937873101" ID="1014901" TEXT="Attribute g e x f">
</node>
<node CREATED="1557937873101" ID="1014902" TEXT="Attributes">
</node>
<node CREATED="1557937873101" ID="1014903" TEXT="Attvalue">
</node>
<node CREATED="1557937873101" ID="1014904" TEXT="Attvalues">
</node>
<node CREATED="1557937873101" ID="1014905" TEXT="Edge">
</node>
<node CREATED="1557937873101" ID="1014906" TEXT="Edges">
</node>
<node CREATED="1557937873101" ID="1014907" TEXT="Graph">
</node>
<node CREATED="1557937873101" ID="1014908" TEXT="Node">
</node>
<node CREATED="1557937873101" ID="1014909" TEXT="Nodes">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1016200" TEXT="Hypergraph entity">
<node CREATED="1557937873101" ID="1016201" TEXT="Hyperedge">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1010300" TEXT="Listener">
<node CREATED="1557937873101" ID="1010301" TEXT="Listener list">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1014800" TEXT="Natural language">
<node CREATED="1557937873101" ID="1014801" TEXT="Google n l">
</node>
<node CREATED="1557937873101" ID="1014802" TEXT="Open calais">
</node>
<node CREATED="1557937873101" ID="1014803" TEXT="Sentimood">
</node>
<node CREATED="1557937873101" ID="1014804" TEXT="Senti emo lex">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1014000" TEXT="No sql">
<node CREATED="1557937873101" ID="1014001" TEXT="No sql client">
</node>
<node CREATED="1557937873101" ID="1014002" TEXT="Neo4j client">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1003000" TEXT="Or node">
<node CREATED="1557937873101" ID="1003001" TEXT="Or node next">
</node>
<node CREATED="1557937873101" ID="1003002" TEXT="Or node random">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013000" TEXT="Petri net entity">
<node CREATED="1557937873101" ID="1013001" TEXT="Petri net">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013002" TEXT="Place p n">
<node CREATED="1557937873101" ID="1013003" TEXT="Place boolean">
</node>
<node CREATED="1557937873101" ID="1013004" TEXT="Place integer">
</node>
<node CREATED="1557937873101" ID="1013005" TEXT="Place structured">
</node>
<node CREATED="1557937873101" ID="1013006" TEXT="Species">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013007" TEXT="Transition p n">
<node CREATED="1557937873101" ID="1013008" TEXT="Reaction">
</node>
</node>
<node CREATED="1557937873101" ID="1013009" TEXT="Queue transitions">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013010" TEXT="Arc p n">
<node CREATED="1557937873101" ID="1013011" TEXT="Input arc">
</node>
<node CREATED="1557937873101" ID="1013012" TEXT="Output arc">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013013" TEXT="Transitions">
<node CREATED="1557937873101" ID="1013014" TEXT="Reactions">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013015" TEXT="Places">
<node CREATED="1557937873101" ID="1013016" TEXT="Speciez">
</node>
</node>
<node CREATED="1557937873101" ID="1013017" TEXT="Input arcs">
</node>
<node CREATED="1557937873101" ID="1013018" TEXT="Output arcs">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013019" TEXT="Analysis p n">
<node CREATED="1557937873101" ID="1013020" TEXT="Analysis petri net">
</node>
<node CREATED="1557937873101" ID="1013021" TEXT="Analysis c r n">
</node>
<node CREATED="1557937873101" ID="1013022" TEXT="Analysis cat">
</node>
<node CREATED="1557937873101" ID="1013023" TEXT="Analysis mem comp">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013024" TEXT="Pne behavior">
<node CREATED="1557937873101" FOLDED="true" ID="1013025" TEXT="Place behavior">
<node CREATED="1557937873101" ID="1013026" TEXT="Moving place behavior">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013027" TEXT="Transition behavior">
<node CREATED="1557937873101" ID="1013028" TEXT="Moving transition behavior">
</node>
<node CREATED="1557937873101" ID="1013029" TEXT="Firing transition behavior">
</node>
</node>
</node>
<node CREATED="1557937873101" ID="1013030" TEXT="Queue nodes in grid">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1013031" TEXT="Grid owner">
<node CREATED="1557937873101" ID="1013032" TEXT="Constantly stirred pot">
</node>
</node>
<node CREATED="1557937873101" ID="1013033" TEXT="Membrane p n">
</node>
</node>
<node CREATED="1557937873101" ID="1000100" TEXT="Port">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1014500" TEXT="Remote node">
<node CREATED="1557937873101" ID="1014501" TEXT="Cross app">
</node>
<node CREATED="1557937873101" ID="1014502" TEXT="Message channel">
</node>
<node CREATED="1557937873101" ID="1014503" TEXT="Peer j s">
</node>
<node CREATED="1557937873101" ID="1014504" TEXT="Post message">
</node>
<node CREATED="1557937873101" ID="1014505" TEXT="Web r t c">
</node>
</node>
<node CREATED="1557937873101" ID="1010100" TEXT="Role">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1016300" TEXT="Recipe entity">
<node CREATED="1557937873101" FOLDED="true" ID="1016301" TEXT="Recipe book">
<node CREATED="1557937873101" ID="1016302" TEXT="Minecraft style recipe book">
</node>
<node CREATED="1557937873101" ID="1016303" TEXT="Json rules engine recipe book">
</node>
<node CREATED="1557937873101" ID="1016304" TEXT="Ceptre json rules engine recipe book">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1016000" TEXT="Room entity">
<node CREATED="1557937873101" ID="1016001" TEXT="Room e trice">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1014300" TEXT="Script">
<node CREATED="1557937873101" ID="1014301" TEXT="Script">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1014600" TEXT="Spreadsheet entity">
<node CREATED="1557937873101" ID="1014601" TEXT="Workbook">
</node>
<node CREATED="1557937873101" ID="1014602" TEXT="Spreadsheet">
</node>
<node CREATED="1557937873101" ID="1014603" TEXT="Spreadsheet row">
</node>
<node CREATED="1557937873101" ID="1014604" TEXT="Spreadsheet cell">
</node>
<node CREATED="1557937873101" ID="1014605" TEXT="Spreadsheet formula">
</node>
<node CREATED="1557937873101" ID="1014606" TEXT="Srw">
</node>
<node CREATED="1557937873101" ID="1014607" TEXT="Scl">
</node>
<node CREATED="1557937873101" ID="1014608" TEXT="Sfr">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1000000" TEXT="State machine entity">
<node CREATED="1557937873101" ID="1000001" TEXT="State machine">
</node>
<node CREATED="1557937873101" ID="1000002" TEXT="Region">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1000003" TEXT="Vertex">
<node CREATED="1557937873101" ID="1000004" TEXT="Connection point reference">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1000005" TEXT="State">
<node CREATED="1557937873101" ID="1000006" TEXT="Final state">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1000007" TEXT="Pseudostate">
<node CREATED="1557937873101" ID="1000008" TEXT="Pseudostate terminate">
</node>
<node CREATED="1557937873101" ID="1000009" TEXT="Pseudostate shallow history">
</node>
<node CREATED="1557937873101" ID="1000010" TEXT="Pseudostate junction">
</node>
<node CREATED="1557937873101" ID="1000011" TEXT="Pseudostate join">
</node>
<node CREATED="1557937873101" ID="1000012" TEXT="Pseudostate initial">
</node>
<node CREATED="1557937873101" ID="1000013" TEXT="Pseudostate fork">
</node>
<node CREATED="1557937873101" ID="1000014" TEXT="Pseudostate exit point">
</node>
<node CREATED="1557937873101" ID="1000015" TEXT="Pseudostate entry point">
</node>
<node CREATED="1557937873101" ID="1000016" TEXT="Pseudostate deep history">
</node>
<node CREATED="1557937873101" ID="1000017" TEXT="Pseudostate choice">
</node>
</node>
</node>
<node CREATED="1557937873101" ID="1000018" TEXT="Trigger">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1000019" TEXT="Transition">
<node CREATED="1557937873101" ID="1000020" TEXT="Transition external">
</node>
<node CREATED="1557937873101" ID="1000021" TEXT="Transition internal">
</node>
<node CREATED="1557937873101" ID="1000022" TEXT="Transition local">
</node>
</node>
<node CREATED="1557937873101" ID="1000023" TEXT="Activity">
</node>
<node CREATED="1557937873101" ID="1000024" TEXT="Guard">
</node>
<node CREATED="1557937873101" ID="1000025" TEXT="Entry activity">
</node>
<node CREATED="1557937873101" ID="1000026" TEXT="Exit activity">
</node>
<node CREATED="1557937873101" ID="1000027" TEXT="Do activity">
</node>
<node CREATED="1557937873101" ID="1000028" TEXT="Deferrable trigger">
</node>
<node CREATED="1557937873101" ID="1000029" TEXT="Target">
</node>
</node>
<node CREATED="1557937873101" ID="1010200" TEXT="Uid">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1016100" TEXT="Xholon base">
<node CREATED="1557937873101" ID="1016101" TEXT="Xholon null">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1004100" TEXT="Xholon collection">
<node CREATED="1557937873101" ID="1004101" TEXT="Xholon list">
</node>
<node CREATED="1557937873101" ID="1004102" TEXT="Xholon map">
</node>
<node CREATED="1557937873101" ID="1004103" TEXT="Xholon set">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1011200" TEXT="Xholon framework">
<node CREATED="1557937873101" ID="1011201" TEXT="Inheritance hierarchy">
</node>
<node CREATED="1557937873101" ID="1011202" TEXT="Tree node factory">
</node>
<node CREATED="1557937873101" ID="1011203" TEXT="Queue">
</node>
<node CREATED="1557937873101" ID="1011204" TEXT="Synchronized queue">
</node>
<node CREATED="1557937873101" ID="1011205" TEXT="Xholon node">
</node>
<node CREATED="1557937873101" ID="1011206" TEXT="Message">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1010700" TEXT="Xholon service">
<node CREATED="1557937873101" FOLDED="true" ID="1010701" TEXT="Xholon internal service">
<node CREATED="1557937873101" ID="1010702" TEXT="Service locator service">
</node>
<node CREATED="1557937873101" ID="1010703" TEXT="Xholon directory service">
</node>
<node CREATED="1557937873101" ID="1010704" TEXT="Dummy service">
</node>
<node CREATED="1557937873101" ID="1010705" TEXT="Tree processor service">
</node>
<node CREATED="1557937873101" ID="1010706" TEXT="About service">
</node>
<node CREATED="1557937873101" ID="1010707" TEXT="Chart viewer service">
</node>
<node CREATED="1557937873101" ID="1010708" TEXT="Spring framework service">
</node>
<node CREATED="1557937873101" ID="1010709" TEXT="Node selection service">
</node>
<node CREATED="1557937873101" ID="1010710" TEXT="Xholon helper service">
</node>
<node CREATED="1557937873101" ID="1010711" TEXT="Wiring service">
</node>
<node CREATED="1557937873101" ID="1010712" TEXT="Control service">
</node>
<node CREATED="1557937873101" ID="1010713" TEXT="Script service">
</node>
<node CREATED="1557937873101" ID="1010714" TEXT="Css service">
</node>
<node CREATED="1557937873101" ID="1010715" TEXT="Media service">
</node>
<node CREATED="1557937873101" ID="1010716" TEXT="Game engine service">
</node>
<node CREATED="1557937873101" ID="1010717" TEXT="Net logo service">
</node>
<node CREATED="1557937873101" ID="1010718" TEXT="Svg view service">
</node>
<node CREATED="1557937873101" ID="1010719" TEXT="Gist service">
</node>
<node CREATED="1557937873101" ID="1010720" TEXT="External format service">
</node>
<node CREATED="1557937873101" ID="1010721" TEXT="Search engine service">
</node>
<node CREATED="1557937873101" ID="1010722" TEXT="Record playback service">
</node>
<node CREATED="1557937873101" ID="1010723" TEXT="Semantic web service">
</node>
<node CREATED="1557937873101" ID="1010724" TEXT="Sbml service">
</node>
<node CREATED="1557937873101" ID="1010725" TEXT="Math sci eng service">
</node>
<node CREATED="1557937873101" ID="1010726" TEXT="Blackboard service">
</node>
<node CREATED="1557937873101" ID="1010727" TEXT="Vfs service">
</node>
<node CREATED="1557937873101" ID="1010728" TEXT="No sql service">
</node>
<node CREATED="1557937873101" ID="1010729" TEXT="Rest service">
</node>
<node CREATED="1557937873101" ID="1010730" TEXT="Blueprints service">
</node>
<node CREATED="1557937873101" ID="1010731" TEXT="Xml database service">
</node>
<node CREATED="1557937873101" ID="1010732" TEXT="Jcr service">
</node>
<node CREATED="1557937873101" ID="1010733" TEXT="Java serialization service">
</node>
<node CREATED="1557937873101" ID="1010734" TEXT="Berkeley db service">
</node>
<node CREATED="1557937873101" ID="1010735" TEXT="Timeline service">
</node>
<node CREATED="1557937873101" ID="1010736" TEXT="Validation service">
</node>
<node CREATED="1557937873101" ID="1010737" TEXT="Xml validation service">
</node>
<node CREATED="1557937873101" ID="1010738" TEXT="Database service">
</node>
<node CREATED="1557937873101" ID="1010739" TEXT="Generic viewer service">
</node>
<node CREATED="1557937873101" ID="1010740" TEXT="Grid viewer service">
</node>
<node CREATED="1557937873101" ID="1010741" TEXT="Vrml service">
</node>
<node CREATED="1557937873101" ID="1010742" TEXT="Graphical network viewer service">
</node>
<node CREATED="1557937873101" ID="1010743" TEXT="Log service">
</node>
<node CREATED="1557937873101" ID="1010744" TEXT="Reflection service">
</node>
<node CREATED="1557937873101" ID="1010745" TEXT="Xholon2 xml service">
</node>
<node CREATED="1557937873101" ID="1010746" TEXT="Xholon creation service">
</node>
<node CREATED="1557937873101" ID="1010747" TEXT="Xml reader service">
</node>
<node CREATED="1557937873101" ID="1010748" TEXT="Xml writer service">
</node>
<node CREATED="1557937873101" ID="1010749" TEXT="Xml2 xholon service">
</node>
<node CREATED="1557937873101" ID="1010750" TEXT="X path service">
</node>
<node CREATED="1557937873101" ID="1010751" TEXT="X query service">
</node>
<node CREATED="1557937873101" ID="1010752" TEXT="Meteor platform service">
</node>
<node CREATED="1557937873101" ID="1010753" TEXT="Remote node service">
</node>
<node CREATED="1557937873101" ID="1010754" TEXT="Broadcast service">
</node>
<node CREATED="1557937873101" ID="1010755" TEXT="Spreadsheet service">
</node>
<node CREATED="1557937873101" ID="1010756" TEXT="Natural language service">
</node>
<node CREATED="1557937873101" ID="1010757" TEXT="Recipe service">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1010758" TEXT="H t m l5 service">
<node CREATED="1557937873101" ID="1010759" TEXT="Web cryptography service">
</node>
<node CREATED="1557937873101" ID="1010760" TEXT="Indexed d b service">
</node>
</node>
<node CREATED="1557937873101" ID="1010761" TEXT="Xholon2 svg">
</node>
<node CREATED="1557937873101" ID="1010762" TEXT="Xholon2 properties">
</node>
</node>
<node CREATED="1557937873101" ID="1010763" TEXT="Xholon internal services">
</node>
<node CREATED="1557937873101" ID="1010764" TEXT="Xholon user service">
</node>
<node CREATED="1557937873101" ID="1010765" TEXT="Xholon user services">
</node>
<node CREATED="1557937873101" ID="1010766" TEXT="Xholon service impl">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1010800" TEXT="X path">
<node CREATED="1557937873101" ID="1010801" TEXT="Pcs path">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="2000100" TEXT="Xholon viewer">
<node CREATED="1557937873101" FOLDED="true" ID="1000200" TEXT="Data plotter">
<node CREATED="1557937873101" ID="1000201" TEXT="X y chart">
</node>
<node CREATED="1557937873101" ID="1000202" TEXT="X axis label">
</node>
<node CREATED="1557937873101" ID="1000203" TEXT="Y axis label">
</node>
<node CREATED="1557937873101" ID="1000204" TEXT="X y series">
</node>
</node>
<node CREATED="1557937873101" ID="1000500" TEXT="Grid viewer">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1002100" TEXT="Histogram viewer">
<node CREATED="1557937873101" ID="1002101" TEXT="X axis label_ hist">
</node>
<node CREATED="1557937873101" ID="1002102" TEXT="Y axis label_ hist">
</node>
</node>
<node CREATED="1557937873101" ID="1000600" TEXT="Interactions">
</node>
<node CREATED="1557937873101" ID="1000700" TEXT="Snapshot">
</node>
<node CREATED="1557937873101" FOLDED="true" ID="1011600" TEXT="Svg entity">
<node CREATED="1557937873101" ID="1011601" TEXT="Svg label">
</node>
<node CREATED="1557937873101" ID="1011602" TEXT="Svg viewable">
</node>
<node CREATED="1557937873101" ID="1011603" TEXT="Svg attribute">
</node>
<node CREATED="1557937873101" ID="1011604" TEXT="Svg client">
</node>
</node>
<node CREATED="1557937873101" ID="1000800" TEXT="Text tree">
</node>
</node>
<node CREATED="1557937873101" ID="1" TEXT="Hello world system">
</node>
<node CREATED="1557937873101" ID="2" TEXT="Hello">
</node>
<node CREATED="1557937873101" ID="3" TEXT="World">
</node>
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="11" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="0" TEXT=" ">
<node CREATED="1557937873101" FOLDED="true" ID="0" TEXT=" ">
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
</node>
<node CREATED="1557937873101" FOLDED="true" ID="0" TEXT=" ">
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
<node CREATED="1557937873101" ID="0" TEXT=" ">
</node>
</node>
</node>
</node>
</node>
</node>
</map>

