<map version="0.9.0">
<!-- To view this file, download free mind mapping software:
 FreeMind from http://freemind.sourceforge.net/wiki/index.php/Main_Page or
 Freeplane from http://freeplane.sourceforge.net/wiki/index.php/Main_Page

Automatically generated by Xholon version 0.9.1, using Xholon2MindMap.java
Sun Aug 13 10:21:14 GMT-400 2017 1502634074935
model: MathML test1
www.primordion.com/Xholon
-->
<node CREATED="1502634074935" ID="0" TEXT="MathML_Test1 154.1">
<node CREATED="1502634074935" FOLDED="true" ID="1" POSITION="right" TEXT="math 154.1">
<node CREATED="1502634074935" FOLDED="true" ID="2" TEXT="apply 154.1">
<node CREATED="1502634074935" ID="3" TEXT="plus 154.1">
</node>
<node CREATED="1502634074935" ID="4" TEXT="cn 5.1">
</node>
<node CREATED="1502634074935" ID="5" TEXT="cn 2">
</node>
<node CREATED="1502634074935" ID="6" TEXT="cn 3">
</node>
<node CREATED="1502634074935" FOLDED="true" ID="7" TEXT="apply 144">
<node CREATED="1502634074935" ID="8" TEXT="times 144">
</node>
<node CREATED="1502634074935" ID="9" TEXT="cn 8">
</node>
<node CREATED="1502634074935" ID="10" TEXT="cn 9">
</node>
<node CREATED="1502634074935" FOLDED="true" ID="11" TEXT="apply 2">
<node CREATED="1502634074935" ID="12" TEXT="abs 2">
</node>
<node CREATED="1502634074935" ID="13" TEXT="cn -2">
</node>
</node>
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="14" POSITION="right" TEXT="math 120">
<node CREATED="1502634074935" FOLDED="true" ID="15" TEXT="apply 120">
<node CREATED="1502634074935" ID="16" TEXT="factorial 120">
</node>
<node CREATED="1502634074935" ID="17" TEXT="cn 5">
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="18" POSITION="right" TEXT="math 4">
<node CREATED="1502634074935" FOLDED="true" ID="19" TEXT="apply 4">
<node CREATED="1502634074935" ID="20" TEXT="minus 4">
</node>
<node CREATED="1502634074935" ID="21" TEXT="cn 7">
</node>
<node CREATED="1502634074935" ID="22" TEXT="cn 3">
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="23" POSITION="right" TEXT="math 2.6">
<node CREATED="1502634074935" FOLDED="true" ID="24" TEXT="apply 2.6">
<node CREATED="1502634074935" ID="25" TEXT="divide 2.6">
</node>
<node CREATED="1502634074935" ID="26" TEXT="cn 13">
</node>
<node CREATED="1502634074935" ID="27" TEXT="cn 5">
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="28" POSITION="right" TEXT="math 8">
<node CREATED="1502634074935" FOLDED="true" ID="29" TEXT="apply 8">
<node CREATED="1502634074935" ID="30" TEXT="power 8">
</node>
<node CREATED="1502634074935" ID="31" TEXT="cn 2">
</node>
<node CREATED="1502634074935" ID="32" TEXT="cn 3">
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="33" POSITION="right" TEXT="TestCi 666">
<node CREATED="1502634074935" FOLDED="true" ID="34" TEXT="math 666">
<node CREATED="1502634074935" FOLDED="true" ID="35" TEXT="apply 666">
<node CREATED="1502634074935" ID="36" TEXT="plus 666">
</node>
<node CREATED="1502634074935" ID="37" TEXT="ci 153">
<arrowlink COLOR="#6666ff" DESTINATION="33" ENDARROW="Default" ID="37330" STARTARROW="None"/>
</node>
<node CREATED="1502634074935" ID="38" TEXT="ci 513">
<arrowlink COLOR="#6666ff" DESTINATION="33" ENDARROW="Default" ID="38330" STARTARROW="None"/>
</node>
</node>
</node>
</node>
</node>
</map>

