<map version="0.9.0">
<!-- To view this file, download free mind mapping software:
 FreeMind from http://freemind.sourceforge.net/wiki/index.php/Main_Page or
 Freeplane from http://freeplane.sourceforge.net/wiki/index.php/Main_Page

Automatically generated by Xholon version 0.9.1, using Xholon2MindMap.java
Sun Aug 13 07:32:09 GMT-400 2017 1502623929571
model: MathML test1
www.primordion.com/Xholon
-->
<node CREATED="1502623929571" ID="0" TEXT="MathML_Test1">
<node CREATED="1502623929571" FOLDED="true" ID="1" POSITION="right" TEXT="math">
<node CREATED="1502623929571" FOLDED="true" ID="2" TEXT="apply">
<node CREATED="1502623929571" ID="3" TEXT="plus">
</node>
<node CREATED="1502623929571" ID="4" TEXT="cn">
</node>
<node CREATED="1502623929571" ID="5" TEXT="cn">
</node>
<node CREATED="1502623929571" ID="6" TEXT="cn">
</node>
<node CREATED="1502623929571" FOLDED="true" ID="7" TEXT="apply">
<node CREATED="1502623929571" ID="8" TEXT="times">
</node>
<node CREATED="1502623929571" ID="9" TEXT="cn">
</node>
<node CREATED="1502623929571" ID="10" TEXT="cn">
</node>
<node CREATED="1502623929571" FOLDED="true" ID="11" TEXT="apply">
<node CREATED="1502623929571" ID="12" TEXT="abs">
</node>
<node CREATED="1502623929571" ID="13" TEXT="cn">
</node>
</node>
</node>
</node>
</node>
<node CREATED="1502623929571" FOLDED="true" ID="14" POSITION="right" TEXT="math">
<node CREATED="1502623929571" FOLDED="true" ID="15" TEXT="apply">
<node CREATED="1502623929571" ID="16" TEXT="factorial">
</node>
<node CREATED="1502623929571" ID="17" TEXT="cn">
</node>
</node>
</node>
<node CREATED="1502623929571" FOLDED="true" ID="18" POSITION="right" TEXT="math">
<node CREATED="1502623929571" FOLDED="true" ID="19" TEXT="apply">
<node CREATED="1502623929571" ID="20" TEXT="minus">
</node>
<node CREATED="1502623929571" ID="21" TEXT="cn">
</node>
<node CREATED="1502623929571" ID="22" TEXT="cn">
</node>
</node>
</node>
<node CREATED="1502623929571" FOLDED="true" ID="23" POSITION="right" TEXT="math">
<node CREATED="1502623929571" FOLDED="true" ID="24" TEXT="apply">
<node CREATED="1502623929571" ID="25" TEXT="divide">
</node>
<node CREATED="1502623929571" ID="26" TEXT="cn">
</node>
<node CREATED="1502623929571" ID="27" TEXT="cn">
</node>
</node>
</node>
<node CREATED="1502623929571" FOLDED="true" ID="28" POSITION="right" TEXT="math">
<node CREATED="1502623929571" FOLDED="true" ID="29" TEXT="apply">
<node CREATED="1502623929571" ID="30" TEXT="power">
</node>
<node CREATED="1502623929571" ID="31" TEXT="cn">
</node>
<node CREATED="1502623929571" ID="32" TEXT="cn">
</node>
</node>
</node>
<node CREATED="1502623929571" FOLDED="true" ID="33" POSITION="right" TEXT="TestCi">
<node CREATED="1502623929571" FOLDED="true" ID="34" TEXT="math">
<node CREATED="1502623929571" FOLDED="true" ID="35" TEXT="apply">
<node CREATED="1502623929571" ID="36" TEXT="plus">
</node>
<node CREATED="1502623929571" ID="37" TEXT="ci">
<arrowlink COLOR="#6666ff" DESTINATION="33" ENDARROW="Default" ID="37330" STARTARROW="None"/>
</node>
<node CREATED="1502623929571" ID="38" TEXT="ci">
<arrowlink COLOR="#6666ff" DESTINATION="33" ENDARROW="Default" ID="38330" STARTARROW="None"/>
</node>
</node>
</node>
</node>
</node>
</map>

