<map version="0.9.0">
<!-- To view this file, download free mind mapping software:
 FreeMind from http://freemind.sourceforge.net/wiki/index.php/Main_Page or
 Freeplane from http://freeplane.sourceforge.net/wiki/index.php/Main_Page

Automatically generated by Xholon version 0.9.1, using Xholon2MindMap.java
Sun Aug 13 10:21:14 GMT-400 2017 1502634074935
model: MathML test1
www.primordion.com/Xholon
-->
<node CREATED="1502634074935" ID="0" TEXT="MathML_Test1">
<node CREATED="1502634074935" FOLDED="true" ID="1" POSITION="right" TEXT="math 154.1">
<node CREATED="1502634074935" FOLDED="true" ID="2" TEXT="apply">
<node CREATED="1502634074935" ID="3" TEXT="plus">
</node>
<node CREATED="1502634074935" ID="4" TEXT="5.1">
</node>
<node CREATED="1502634074935" ID="5" TEXT="2">
</node>
<node CREATED="1502634074935" ID="6" TEXT="3">
</node>
<node CREATED="1502634074935" FOLDED="true" ID="7" TEXT="apply">
<node CREATED="1502634074935" ID="8" TEXT="times">
</node>
<node CREATED="1502634074935" ID="9" TEXT="8">
</node>
<node CREATED="1502634074935" ID="10" TEXT="9">
</node>
<node CREATED="1502634074935" FOLDED="true" ID="11" TEXT="apply">
<node CREATED="1502634074935" ID="12" TEXT="abs">
</node>
<node CREATED="1502634074935" ID="13" TEXT="-2">
</node>
</node>
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="14" POSITION="right" TEXT="math 120">
<node CREATED="1502634074935" FOLDED="true" ID="15" TEXT="apply">
<node CREATED="1502634074935" ID="16" TEXT="factorial">
</node>
<node CREATED="1502634074935" ID="17" TEXT="5">
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="18" POSITION="right" TEXT="math 4">
<node CREATED="1502634074935" FOLDED="true" ID="19" TEXT="apply">
<node CREATED="1502634074935" ID="20" TEXT="minus">
</node>
<node CREATED="1502634074935" ID="21" TEXT="7">
</node>
<node CREATED="1502634074935" ID="22" TEXT="3">
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="23" POSITION="right" TEXT="math 2.6">
<node CREATED="1502634074935" FOLDED="true" ID="24" TEXT="apply">
<node CREATED="1502634074935" ID="25" TEXT="divide">
</node>
<node CREATED="1502634074935" ID="26" TEXT="13">
</node>
<node CREATED="1502634074935" ID="27" TEXT="5">
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="28" POSITION="right" TEXT="math 8">
<node CREATED="1502634074935" FOLDED="true" ID="29" TEXT="apply">
<node CREATED="1502634074935" ID="30" TEXT="power">
</node>
<node CREATED="1502634074935" ID="31" TEXT="2">
</node>
<node CREATED="1502634074935" ID="32" TEXT="3">
</node>
</node>
</node>
<node CREATED="1502634074935" FOLDED="true" ID="33" POSITION="right" TEXT="TestCi">
<node CREATED="1502634074935" FOLDED="true" ID="34" TEXT="math 666">
<node CREATED="1502634074935" FOLDED="true" ID="35" TEXT="apply">
<node CREATED="1502634074935" ID="36" TEXT="plus">
</node>
<node CREATED="1502634074935" ID="37" TEXT="153">
<arrowlink COLOR="#6666ff" DESTINATION="33" ENDARROW="Default" ID="37330" STARTARROW="None"/>
</node>
<node CREATED="1502634074935" ID="38" TEXT="513">
<arrowlink COLOR="#6666ff" DESTINATION="33" ENDARROW="Default" ID="38330" STARTARROW="None"/>
</node>
</node>
</node>
</node>
</node>
</map>

