<map version="0.9.0">
<!-- To view this file, download free mind mapping software:
 FreeMind from http://freemind.sourceforge.net/wiki/index.php/Main_Page or
 Freeplane from http://freeplane.sourceforge.net/wiki/index.php/Main_Page

Automatically generated by Xholon version 0.9.1, using Xholon2MindMap.java
Fri May 11 15:12:58 GMT-400 2018 1526065978708
model: Recipes - Petri Nets
www.primordion.com/Xholon
-->
<node CREATED="1526065978708" ID="46">
<richcontent TYPE="NODE"><html><head></head><body><p>
crema di mascarpone <font size="2">example from Paweł Sobocinski blog</font>
</p></body></html></richcontent>
<node CREATED="1526065978708" ID="49" POSITION="right" TEXT="AnalysisCRN">
</node>
<node CREATED="1526065978708" ID="50" POSITION="right" TEXT="Transitions">
<node CREATED="1526065978708" ID="51" TEXT="Crack Egg">
<arrowlink COLOR="#B22222" DESTINATION="89" ENDARROW="None" ID="51890" STARTARROW="Default"/>
<arrowlink COLOR="#000080" DESTINATION="93" ENDARROW="Default" ID="51930" STARTARROW="None"/>
<arrowlink COLOR="#000080" DESTINATION="94" ENDARROW="Default" ID="51940" STARTARROW="None"/>
</node>
<node CREATED="1526065978708" ID="57" TEXT="Crack Egg">
<arrowlink COLOR="#B22222" DESTINATION="90" ENDARROW="None" ID="57900" STARTARROW="Default"/>
<arrowlink COLOR="#000080" DESTINATION="95" ENDARROW="Default" ID="57950" STARTARROW="None"/>
<arrowlink COLOR="#000080" DESTINATION="96" ENDARROW="Default" ID="57960" STARTARROW="None"/>
</node>
<node CREATED="1526065978708" ID="63" TEXT="Whisk">
<arrowlink COLOR="#B22222" DESTINATION="93" ENDARROW="None" ID="63930" STARTARROW="Default"/>
<arrowlink COLOR="#B22222" DESTINATION="95" ENDARROW="None" ID="63950" STARTARROW="Default"/>
<arrowlink COLOR="#000080" DESTINATION="97" ENDARROW="Default" ID="63970" STARTARROW="None"/>
</node>
<node CREATED="1526065978708" ID="69" TEXT="Beat">
<arrowlink COLOR="#B22222" DESTINATION="94" ENDARROW="None" ID="69940" STARTARROW="Default"/>
<arrowlink COLOR="#B22222" DESTINATION="96" ENDARROW="None" ID="69960" STARTARROW="Default"/>
<arrowlink COLOR="#B22222" DESTINATION="91" ENDARROW="None" ID="69910" STARTARROW="Default"/>
<arrowlink COLOR="#000080" DESTINATION="98" ENDARROW="Default" ID="69980" STARTARROW="None"/>
</node>
<node CREATED="1526065978708" ID="76" TEXT="Stir">
<arrowlink COLOR="#B22222" DESTINATION="98" ENDARROW="None" ID="76980" STARTARROW="Default"/>
<arrowlink COLOR="#B22222" DESTINATION="92" ENDARROW="None" ID="76920" STARTARROW="Default"/>
<arrowlink COLOR="#000080" DESTINATION="99" ENDARROW="Default" ID="76990" STARTARROW="None"/>
</node>
<node CREATED="1526065978708" ID="82" TEXT="Fold">
<arrowlink COLOR="#B22222" DESTINATION="97" ENDARROW="None" ID="82970" STARTARROW="Default"/>
<arrowlink COLOR="#B22222" DESTINATION="99" ENDARROW="None" ID="82990" STARTARROW="Default"/>
<arrowlink COLOR="#000080" DESTINATION="100" ENDARROW="Default" ID="821000" STARTARROW="None"/>
</node>
</node>
<node CREATED="1526065978708" ID="88" POSITION="right" TEXT="Places">
<node CREATED="1526065978708" ID="89" TEXT="egg">
</node>
<node CREATED="1526065978708" ID="90" TEXT="egg">
</node>
<node CREATED="1526065978708" ID="91" TEXT="sugar">
</node>
<node CREATED="1526065978708" ID="92" TEXT="mascarpone">
</node>
<node CREATED="1526065978708" ID="93" TEXT="white">
</node>
<node CREATED="1526065978708" ID="94" TEXT="yolk">
</node>
<node CREATED="1526065978708" ID="95" TEXT="white">
</node>
<node CREATED="1526065978708" ID="96" TEXT="yolk">
</node>
<node CREATED="1526065978708" ID="97" TEXT="whisked whites">
</node>
<node CREATED="1526065978708" ID="98" TEXT="yolky paste">
</node>
<node CREATED="1526065978708" ID="99" TEXT="thick paste">
</node>
<node CREATED="1526065978708" ID="100" TEXT="crema di mascarpone">
</node>
</node>
</node>
</map>
