<map version="1.0.1">
<!-- To view this file, download free mind mapping software:
 FreeMind from http://freemind.sourceforge.net/wiki/index.php/Main_Page or
 Freeplane from http://freeplane.sourceforge.net/wiki/index.php/Main_Page

Automatically generated by Xholon version 0.9.1, using Xholon2MindMap.java
Thu Dec 22 09:41:05 GMT-500 2016 1482417665447
model: Relationships
www.primordion.com/Xholon
-->
<node CREATED="1482417665447" ID="44" TEXT="Physical system">
<node CREATED="1482417665447" FOLDED="true" ID="45" POSITION="right" TEXT="People">
<node CREATED="1482417665447" ID="50" TEXT="Ken">
<arrowlink COLOR="#6666ff" DESTINATION="51" MIDDLE_LABEL="friend" ENDARROW="Default" ID="50510" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="61" MIDDLE_LABEL="daughter" ENDARROW="Default" ID="50611" STARTARROW="None"/>
</node>
<node CREATED="1482417665447" ID="51" TEXT="Andrea">
<arrowlink COLOR="#6666ff" DESTINATION="52" MIDDLE_LABEL="mother" ENDARROW="Default" ID="51520" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="53" MIDDLE_LABEL="father" ENDARROW="Default" ID="51531" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="54" MIDDLE_LABEL="sister" ENDARROW="Default" ID="51542" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="55" MIDDLE_LABEL="sister" ENDARROW="Default" ID="51553" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="56" MIDDLE_LABEL="brother" ENDARROW="Default" ID="51564" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="57" MIDDLE_LABEL="aunt" ENDARROW="Default" ID="51575" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="58" MIDDLE_LABEL="uncle" ENDARROW="Default" ID="51586" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="66" MIDDLE_LABEL="works" ENDARROW="Default" ID="51667" STARTARROW="None"/>
</node>
<node CREATED="1482417665447" ID="52" TEXT="Kitty">
</node>
<node CREATED="1482417665447" ID="53" TEXT="Harvie">
</node>
<node CREATED="1482417665447" ID="54" TEXT="Hillary">
</node>
<node CREATED="1482417665447" ID="55" TEXT="Jane">
</node>
<node CREATED="1482417665447" ID="56" TEXT="Stephen">
</node>
<node CREATED="1482417665447" ID="57" TEXT="Gwyn">
</node>
<node CREATED="1482417665447" ID="58" TEXT="Dave">
<arrowlink COLOR="#6666ff" DESTINATION="59" MIDDLE_LABEL="daughter" ENDARROW="Default" ID="58590" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="60" MIDDLE_LABEL="daughter" ENDARROW="Default" ID="58601" STARTARROW="None"/>
</node>
<node CREATED="1482417665447" ID="59" TEXT="Allison">
</node>
<node CREATED="1482417665447" ID="60" TEXT="Davez hillary">
</node>
<node CREATED="1482417665447" ID="61" TEXT="Carolyn">
<arrowlink COLOR="#6666ff" DESTINATION="62" MIDDLE_LABEL="husband" ENDARROW="Default" ID="61620" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="63" MIDDLE_LABEL="son" ENDARROW="Default" ID="61631" STARTARROW="None"/>
<arrowlink COLOR="#6666ff" DESTINATION="64" MIDDLE_LABEL="son" ENDARROW="Default" ID="61642" STARTARROW="None"/>
</node>
<node CREATED="1482417665447" ID="62" TEXT="Conan">
</node>
<node CREATED="1482417665447" ID="63" TEXT="Luke">
<arrowlink COLOR="#6666ff" DESTINATION="67" MIDDLE_LABEL="school" ENDARROW="Default" ID="63670" STARTARROW="None"/>
</node>
<node CREATED="1482417665447" ID="64" TEXT="Dylan">
</node>
</node>
<node CREATED="1482417665447" FOLDED="true" ID="46" POSITION="right" TEXT="Organizations">
<node CREATED="1482417665447" ID="66" TEXT="Nav can">
</node>
<node CREATED="1482417665447" ID="67" TEXT="Churchill">
</node>
</node>
</node>
</map>

