<map version="0.9.0">
<!-- To view this file, download free mind mapping software:
 FreeMind from http://freemind.sourceforge.net/wiki/index.php/Main_Page or
 Freeplane from http://freeplane.sourceforge.net/wiki/index.php/Main_Page

Automatically generated by Xholon version 0.9.1, using Xholon2MindMap.java
Sun Feb 04 08:51:43 GMT-500 2018 1517752303428
model: Data Science - Workflow Graphs
www.primordion.com/Xholon
-->
<node CREATED="1517752303428" ID="70" TEXT="Areas of Expertise">
<node CREATED="1517752303428" ID="71" POSITION="right" TEXT="Problem Domain">
</node>
<node CREATED="1517752303428" FOLDED="true" ID="72" POSITION="right" TEXT="Data Collection">
<node CREATED="1517752303428" ID="73" TEXT="API Wrangling">
</node>
<node CREATED="1517752303428" ID="74" TEXT="Web Scraping">
</node>
<node CREATED="1517752303428" ID="75" TEXT="Questionnaire Design + Use">
</node>
<node CREATED="1517752303428" ID="76" TEXT="Sensor Design">
</node>
</node>
<node CREATED="1517752303428" FOLDED="true" ID="77" POSITION="right" TEXT="Data Storage">
<node CREATED="1517752303428" ID="78" TEXT="Database Design">
</node>
<node CREATED="1517752303428" ID="79" TEXT="Streaming Data">
</node>
<node CREATED="1517752303428" ID="80" TEXT="Big Data Wrangling">
</node>
<node CREATED="1517752303428" ID="81" TEXT="Data Querying">
</node>
<node CREATED="1517752303428" ID="82" TEXT="Database Implementation">
</node>
</node>
<node CREATED="1517752303428" FOLDED="true" ID="83" POSITION="right" TEXT="Data Preparation">
<node CREATED="1517752303428" ID="84" TEXT="Evaluating">
</node>
<node CREATED="1517752303428" ID="85" TEXT="Cleaning">
</node>
<node CREATED="1517752303428" ID="86" TEXT="Restructuring">
</node>
<node CREATED="1517752303428" ID="87" TEXT="Condensing">
</node>
<node CREATED="1517752303428" ID="88" TEXT="Transforming">
</node>
</node>
<node CREATED="1517752303428" FOLDED="true" ID="89" POSITION="right" TEXT="Data Analysis">
<node CREATED="1517752303428" ID="90" TEXT="Classification">
</node>
<node CREATED="1517752303428" ID="91" TEXT="Clustering">
</node>
<node CREATED="1517752303428" ID="92" TEXT="Conceptual Analysis">
</node>
<node CREATED="1517752303428" ID="93" TEXT="Value Estimation">
</node>
<node CREATED="1517752303428" ID="94" TEXT="Anomaly Detection">
</node>
<node CREATED="1517752303428" ID="95" TEXT="Algorithm Performance">
</node>
<node CREATED="1517752303428" ID="96" TEXT="Text Mining">
</node>
<node CREATED="1517752303428" ID="97" TEXT="Sentiment Analysis">
</node>
</node>
<node CREATED="1517752303428" FOLDED="true" ID="98" POSITION="right" TEXT="Data Presentation">
<node CREATED="1517752303428" ID="99" TEXT="Web Apps">
</node>
<node CREATED="1517752303428" ID="100" TEXT="Dashboard Design">
</node>
<node CREATED="1517752303428" ID="101" TEXT="Data Visualization">
</node>
<node CREATED="1517752303428" ID="102" TEXT="UX">
</node>
<node CREATED="1517752303428" ID="103" TEXT="Infographics">
</node>
</node>
</node>
</map>

