<map version="0.9.0">
<!-- To view this file, download free mind mapping software:
 FreeMind from http://freemind.sourceforge.net/wiki/index.php/Main_Page or
 Freeplane from http://freeplane.sourceforge.net/wiki/index.php/Main_Page

Automatically generated by Xholon version 0.9.1, using Xholon2MindMap.java
Wed Nov 20 14:16:54 GMT-500 2019 1574277414658
model: Seven Sketches book - Example 1.56 (The tree of life)
www.primordion.com/Xholon
-->
<node CREATED="1574277414658" ID="7" TEXT="mammal">
<node CREATED="1574277414658" FOLDED="true" ID="8" POSITION="left" TEXT="primate">
<node CREATED="1574277414658" FOLDED="true" ID="9" TEXT="homo">
<node CREATED="1574277414658" ID="10" TEXT="sapiens">
</node>
<node CREATED="1574277414658" ID="11" TEXT="habilis">
</node>
</node>
</node>
<node CREATED="1574277414658" FOLDED="true" ID="12" POSITION="left" TEXT="carnivore">
<node CREATED="1574277414658" FOLDED="true" ID="13" TEXT="panthera">
<node CREATED="1574277414658" ID="14" TEXT="lion">
</node>
<node CREATED="1574277414658" ID="15" TEXT="tiger">
</node>
</node>
</node>
</node>
</map>

