/* 
To view this file, download an open-source relational database product such as mysql or postgresql.

Automatically generated by Xholon version 0.9.1, using Xholon2Sql.java
Sat Jun 10 09:54:49 GMT-400 2017 1497102889955
model: Categorical Data IDE - AQL - Sigma
www.primordion.com/Xholon
In MySQL, you will need to temporarily disable foreign keys while loading in this file:
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS=0;
source thenameofthisfile.sql;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
 */
DROP TABLE IF EXISTS CatTheoryInstance;
CREATE TABLE IF NOT EXISTS CatTheoryInstance (
 ID int NOT NULL,
 xhcID int NOT NULL,
 $H int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID));
INSERT INTO CatTheoryInstance (ID, xhcID, $H) VALUES
 (75, 8, 1364);

DROP TABLE IF EXISTS Amphibian;
CREATE TABLE IF NOT EXISTS Amphibian (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 attA varchar(80) NOT NULL default '',
 IsAL int,
 IsAW int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID),
 FOREIGN KEY (IsAL) REFERENCES LandAnimal(ID),
 FOREIGN KEY (IsAW) REFERENCES WaterAnimal(ID));
INSERT INTO Amphibian (ID, xhcID, roleName, attA, IsAL, IsAW) VALUES
 (52, 10, 'a1', 'gecko', 56, 68);
INSERT INTO Amphibian (ID, xhcID, roleName, attA, IsAL, IsAW) VALUES
 (54, 10, 'a2', 'frog', 58, 70);

DROP TABLE IF EXISTS LandAnimal;
CREATE TABLE IF NOT EXISTS LandAnimal (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 attL varchar(80) NOT NULL default '',
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID));
INSERT INTO LandAnimal (ID, xhcID, roleName, attL) VALUES
 (56, 11, 'l1', 'gecko');
INSERT INTO LandAnimal (ID, xhcID, roleName, attL) VALUES
 (58, 11, 'l2', 'frog');
INSERT INTO LandAnimal (ID, xhcID, roleName, attL) VALUES
 (60, 11, 'l3', 'human');
INSERT INTO LandAnimal (ID, xhcID, roleName, attL) VALUES
 (62, 11, 'l4', 'cow');
INSERT INTO LandAnimal (ID, xhcID, roleName, attL) VALUES
 (64, 11, 'l5', 'horse');

DROP TABLE IF EXISTS WaterAnimal;
CREATE TABLE IF NOT EXISTS WaterAnimal (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 attW varchar(80) NOT NULL default '',
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID));
INSERT INTO WaterAnimal (ID, xhcID, roleName, attW) VALUES
 (66, 12, 'w1', 'fish');
INSERT INTO WaterAnimal (ID, xhcID, roleName, attW) VALUES
 (68, 12, 'w2', 'gecko');
INSERT INTO WaterAnimal (ID, xhcID, roleName, attW) VALUES
 (70, 12, 'w3', 'frog');
INSERT INTO WaterAnimal (ID, xhcID, roleName, attW) VALUES
 (72, 12, 'w4', 'dolphin');

DROP TABLE IF EXISTS XholonClass;
CREATE TABLE IF NOT EXISTS XholonClass (
 ID int NOT NULL,
 xhcName varchar(80),
 parentID int,
 PRIMARY KEY (ID),
 FOREIGN KEY (parentID) REFERENCES XholonClass(ID));
INSERT INTO XholonClass (ID, xhcName, parentID) VALUES
 (0, 'XholonClass', 0),
 (1, 'Chameleon', 0),
 (2, 'Quantity', 0),
 (5, 'PhysicalSystem', 0),
 (6, 'CattSystem', 0),
 (7, 'CatTheorySchema', 0),
 (8, 'CatTheoryInstance', 0),
 (9, 'String', 0),
 (10, 'Amphibian', 0),
 (11, 'LandAnimal', 0),
 (12, 'WaterAnimal', 0);

