/* 
To view this file, download an open-source relational database product such as mysql or postgresql.

Automatically generated by Xholon version 0.9.1, using Xholon2Sql.java
Tue Jun 20 10:34:42 GMT-400 2017 1497969282238
model: AQL - Web Interface
www.primordion.com/Xholon
In MySQL, you will need to temporarily disable foreign keys while loading in this file:
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS=0;
source aqlWebInterface01.sql;
source ~/gwtspace/Xholon/Xholon/exports/sql/aqlWebInterface01.sql;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
 */
DROP TABLE IF EXISTS CatTheoryInstance;
CREATE TABLE IF NOT EXISTS CatTheoryInstance (
 ID int NOT NULL,
 xhcID int NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID));
INSERT INTO CatTheoryInstance (ID, xhcID) VALUES
 (66, 11);

DROP TABLE IF EXISTS One;
CREATE TABLE IF NOT EXISTS One (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 attr1 int,
 fk1 int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID),
 FOREIGN KEY (fk1) REFERENCES Two(ID));
INSERT INTO One (ID, xhcID, roleName, attr1, fk1) VALUES
 (57, 14, 'one1', 4, 61);
INSERT INTO One (ID, xhcID, roleName) VALUES
 (59, 14, 'one2');

DROP TABLE IF EXISTS Two;
CREATE TABLE IF NOT EXISTS Two (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 attr2 varchar(80) NOT NULL default '',
 fk2 int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID),
 FOREIGN KEY (fk2) REFERENCES Three(ID));
INSERT INTO Two (ID, xhcID, roleName, attr2, fk2) VALUES
 (61, 16, 'two1', 'Ken', 63);

DROP TABLE IF EXISTS Three;
CREATE TABLE IF NOT EXISTS Three (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 attr3 varchar(80) NOT NULL default '',
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID));
INSERT INTO Three (ID, xhcID, roleName, attr3) VALUES
 (63, 18, 'three1', 'Licorice');

DROP TABLE IF EXISTS XholonClass;
CREATE TABLE IF NOT EXISTS XholonClass (
 ID int NOT NULL,
 xhcName varchar(80),
 parentID int,
 PRIMARY KEY (ID),
 FOREIGN KEY (parentID) REFERENCES XholonClass(ID));
INSERT INTO XholonClass (ID, xhcName, parentID) VALUES
 (0, 'XholonClass', 0),
 (8, 'Chameleonbehavior', 1001200),
 (1, 'Chameleon', 0),
 (2, 'Quantity', 0),
 (5, 'PhysicalSystem', 0),
 (6, 'PauseButton', 0),
 (7, 'StepButton', 0),
 (9, 'CattSystem', 0),
 (10, 'CatTheorySchema', 0),
 (11, 'CatTheoryInstance', 0),
 (12, 'int', 0),
 (13, 'string', 0),
 (14, 'One', 0),
 (15, 'Ones', 0),
 (16, 'Two', 0),
 (17, 'Twos', 0),
 (18, 'Three', 0),
 (19, 'Threes', 0);

