/* 
To view this file, download an open-source relational database product such as mysql or postgresql.

Automatically generated by Xholon version 0.9.1, using Xholon2Sql.java
Sun May 21 12:30:22 GMT-400 2017 1495384222782
model: Pentagon meeting: A first for members of Trump-Trudeau cabinets
www.primordion.com/Xholon
In MySQL, you will need to temporarily disable foreign keys while loading in this file:
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS=0;
source thenameofthisfile.sql;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
 */
DROP TABLE IF EXISTS Meeting;
CREATE TABLE IF NOT EXISTS Meeting (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID));
INSERT INTO Meeting (ID, xhcID, roleName) VALUES
 (47, 6, 'a meeting at the Pentagon on Monday');

DROP TABLE IF EXISTS Person;
CREATE TABLE IF NOT EXISTS Person (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 parentID int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID),
 FOREIGN KEY (parentID) REFERENCES People(ID));
INSERT INTO Person (ID, xhcID, roleName, parentID) VALUES
 (49, 7, 'James Mattis', 48);
INSERT INTO Person (ID, xhcID, roleName, parentID) VALUES
 (50, 7, 'Harjit Sajjan', 48);

DROP TABLE IF EXISTS MainTopic;
CREATE TABLE IF NOT EXISTS MainTopic (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 parentID int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID),
 FOREIGN KEY (parentID) REFERENCES Topics(ID));
INSERT INTO MainTopic (ID, xhcID, roleName, parentID) VALUES
 (52, 9, 'ongoing commitment to NATO', 51);
INSERT INTO MainTopic (ID, xhcID, roleName, parentID) VALUES
 (53, 9, 'defence spending levels', 51);

DROP TABLE IF EXISTS MinorTopic;
CREATE TABLE IF NOT EXISTS MinorTopic (
 ID int NOT NULL,
 xhcID int NOT NULL,
 roleName varchar(80) NOT NULL default '',
 parentID int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID),
 FOREIGN KEY (parentID) REFERENCES Topics(ID));
INSERT INTO MinorTopic (ID, xhcID, roleName, parentID) VALUES
 (54, 10, 'Canada peacekeeping plans', 51);
INSERT INTO MinorTopic (ID, xhcID, roleName, parentID) VALUES
 (55, 10, 'fighter jet procurement', 51);

DROP TABLE IF EXISTS People;
CREATE TABLE IF NOT EXISTS People (
 ID int NOT NULL,
 xhcID int NOT NULL,
 parentID int,
 discussed int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID),
 FOREIGN KEY (parentID) REFERENCES Meeting(ID),
 FOREIGN KEY (discussed) REFERENCES Topics(ID));
INSERT INTO People (ID, xhcID, parentID, discussed) VALUES
 (48, 11, 47, 51);

DROP TABLE IF EXISTS Topics;
CREATE TABLE IF NOT EXISTS Topics (
 ID int NOT NULL,
 xhcID int NOT NULL,
 parentID int,
 PRIMARY KEY (ID),
 FOREIGN KEY (xhcID) REFERENCES XholonClass(ID),
 FOREIGN KEY (parentID) REFERENCES Meeting(ID));
INSERT INTO Topics (ID, xhcID, parentID) VALUES
 (51, 12, 47);

DROP TABLE IF EXISTS XholonClass;
CREATE TABLE IF NOT EXISTS XholonClass (
 ID int NOT NULL,
 xhcName varchar(80),
 parentID int,
 PRIMARY KEY (ID),
 FOREIGN KEY (parentID) REFERENCES XholonClass(ID));
INSERT INTO XholonClass (ID, xhcName, parentID) VALUES
 (0, 'XholonClass', 0),
 (13, 'PhysicalSystembehavior', 1001200),
 (1, 'Chameleon', 0),
 (2, 'Quantity', 0),
 (5, 'PhysicalSystem', 0),
 (6, 'Meeting', 0),
 (7, 'Person', 0),
 (8, 'Topic', 0),
 (9, 'MainTopic', 8),
 (10, 'MinorTopic', 8),
 (11, 'People', 0),
 (12, 'Topics', 0);

